In [3]:
import os, random
import numpy as np
import pandas as pd
from sklearn.cluster import OPTICS
from sklearn.datasets import make_blobs
from sentence_transformers import SentenceTransformer
from umap import UMAP
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

INPUT_CSV = "/Users/suyashmali/Thesis/LLM/Notebook/Cleaned_Data_New1.csv"
TEXT_COL = "metadata_clean"
LABEL_COL = "Level3"

MIN_SAMPLES = 100
MAX_SAMPLES = 500

# EMBED_MODEL = "all-mpnet-base-v2"
EMBED_MODEL = "all-MiniLM-L6-v2"

In [4]:
df = pd.read_csv(INPUT_CSV)

def min_max_sample(df, label_col, min_k, max_k, seed=42):
    sampled_groups = []
    for label, g in df.groupby(label_col):
        if len(g) < min_k:
            continue
        n = min(len(g), max_k)
        sampled_groups.append(g.sample(n=n, random_state=seed))
    return pd.concat(sampled_groups).reset_index(drop=True)

sample_df = min_max_sample(df, LABEL_COL, MIN_SAMPLES, MAX_SAMPLES)

print("Final sample size:", len(sample_df))
print("Unique Level3 categories:", sample_df[LABEL_COL].nunique())

print(sample_df[[LABEL_COL]].value_counts().head(25))

Final sample size: 43803
Unique Level3 categories: 126
Level3
Wireless Routers                   500
Power Banks                        500
Network Switches                   500
Projector Mounts                   500
Projector Lamps                    500
Household Batteries                500
IT Support Services                500
Projector Accessories              500
Projection Screens                 500
Power Supply Units                 500
Power Distribution Units (PDUs)    500
Power Cables                       500
KVM Switches                       500
Keyboards                          500
Power Adapters & Inverters         500
Flat Panel Spare Parts             500
Portable Speakers                  500
PCs/Workstations                   500
Mice                               500
Mobile Device Chargers             500
PC/Workstation Barebones           500
Mobile Device Keyboards            500
Mobile Headsets                    500
Notebooks                          500
Mobile Phone Cases                 500
Name: count, dtype: int64

In [5]:
sample_df.columns

Index(['Brand', 'BrandPartCode', 'ProductName', 'Description.LongProductName',
       'Description.LongDesc', 'SummaryDescription.LongSummaryDescription',
       'pathlist_names', 'Level1', 'Level2', 'Level3', 'metadata_text',
       'metadata_clean'],
      dtype='object')

In [7]:
def coverage_by_min_k(df, min_k, level3="Level3", level2="Level2", level1="Level1"):
    # keep only Level3 categories with >= min_k products
    filtered = df.groupby(level3).filter(lambda x: len(x) >= min_k)

    return {
        "min_products": min_k,
        "total_products": len(filtered),
        "unique_Level3": filtered[level3].nunique(),
        "unique_Level2": filtered[level2].nunique(),
        "unique_Level1": filtered[level1].nunique(),
    }


min_values = [0, 20, 40, 45, 50, 70, 100, 150]

coverage_table = pd.DataFrame(
    [coverage_by_min_k(df, k) for k in min_values]
)

coverage_table

   min_products  total_products  unique_Level3  unique_Level2  unique_Level1
0             0          289865            209             14              1
1            20          289725            201             14              1
2            40          288693            165             14              1
3            45          288480            160             14              1
4            50          288247            155             13              1
5            70          287483            142             13              1
6           100          286118            126             13              1
7           150          282935            100             13              1

In [8]:
def dropped_categories(df, min_k, level3="Level3"):
    valid = set(
        df.groupby(level3)
        .filter(lambda x: len(x) >= min_k)[level3]
    )
    all_cats = set(df[level3])
    return all_cats - valid

dropped_categories(df, 100)

{'AV Conferencing Bridges',
 'AV Receivers',
 'Activity Trackers',
 'All-in-One PC/Workstation Mounts & Stands',
 'Audio Turntables',
 'Backpack PCs',
 'Bridges & Repeaters',
 'CPU Holders',
 'CRT TVs',
 'Cable Boots',
 'Cable Protectors',
 'Cable Splitters or Combiners',
 'Car Kits',
 'Cassette Players',
 'Computer TV Tuners',
 'Customer Displays',
 'E-Book Readers',
 'Fax Supplies',
 'Fibre Optic Adapters',
 'FireWire Cables',
 'Gateways/Controllers',
 'Handheld Mobile Computer Spare Parts',
 'Handheld Mobile Computers',
 'Head-Mounted Displays',
 'ISDN Access Devices',
 'IT Courses',
 'KVM Extenders',
 "Kids' Tablet Accessories",
 "Kids' Tablets",
 'Lamination Films',
 'Laminator Pouches',
 'MP3/MP4 Player Accessories',
 'Mobile Device Skins',
 'Modems',
 'Monitors CRT',
 'Network Cable Testers',
 'Network Extenders',
 'Network Management Devices',
 'Network Splitters',
 'Network Switch Modules',
 'Notebook Power Tips',
 'Numeric Keypads',
 'Other Input Devices',
 'PS/2 Cables',
 'Paper Shredders',
 'Parallel Cables',
 'Peripheral Device Cases',
 'PoE Adapters',
 'Portable DVD/Blu-Ray Players',
 'Portable Device Management Carts & Cabinets',
 'Projector Cases',
 'Public Address (PA) Systems',
 'Remote Management Adapters',
 'Remote Power Controllers',
 'Ribbon Cables',
 'S-Video Cables',
 'SCART Cables',
 'Selfie Sticks',
 'Service Management Software',
 'Signal Cables',
 'Smart Card Readers',
 'Smart TV Boxes',
 'Sport Watch Accessories',
 'Sport Watches',
 'Stereoscopic 3D Glasses',
 'Stick PCs',
 'TV Set-Top Boxes',
 'Telephony Cables',
 'Television Antennas',
 'Thunderbolt Cables',
 'Touch Pads',
 'Touch Screen Overlays',
 'Two-Way Radios',
 'UPS Battery Cabinets',
 'USB Graphics Adapters',
 'Uninterruptible Power Supplies (UPSs) Accessories',
 'Video Capturing Devices',
 'Video Conferencing Cameras',
 'Video Conferencing Systems',
 'Video Switches',
 'Wireless Presenters',
 'Word Processors',
 'Wrist Rests'}

In [9]:
print(sample_df[[LABEL_COL]].value_counts().head(130))

Level3
Wireless Routers                  500
Power Banks                       500
Network Switches                  500
Projector Mounts                  500
Projector Lamps                   500
                                 ...
Portable Stereo Systems           108
Composite Video Cables            106
Component (YPbPr) Video Cables    104
Mobile Phone Cables               103
Input Device Accessories          100
Name: count, Length: 126, dtype: int64

In [10]:
sample_df["final_text"] = (
    sample_df[TEXT_COL]
    .fillna("")
    .astype(str)
    .str.strip()
)

fallback_cols = ["ProductName", "Title"]

def fallback_text(row):
    if row["final_text"]:
        return row["final_text"]
    return " ".join(
        str(row[c]) for c in fallback_cols
        if c in row and pd.notna(row[c])
    )

sample_df["final_text"] = sample_df.apply(fallback_text, axis=1)

print("Non-empty texts:", sample_df["final_text"].astype(bool).sum())

Non-empty texts: 43803

In [11]:
sample_df["final_text"].head(2)

0    vertiv ems1000t, avocent. type av transmitter,...
1    c2g 29225. type av transmitter, maximum resolu...
Name: final_text, dtype: object

In [12]:
sample_df["metadata_clean"].head(2)

0    vertiv ems1000t, avocent. type av transmitter,...
1    c2g 29225. type av transmitter, maximum resolu...
Name: metadata_clean, dtype: object

In [13]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option("max_colwidth", None)

In [26]:
model = SentenceTransformer(EMBED_MODEL)

embeddings = model.encode(
    sample_df["metadata_clean"].tolist(),
    batch_size=128,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/343 [00:00<?, ?it/s]

Embedding shape: (43803, 384)

In [29]:
umap_model = UMAP(
    n_neighbors=15,
    min_dist=0.0,
    n_components=25,
    metric="cosine",
    random_state=RANDOM_STATE
)

reduced = umap_model.fit_transform(embeddings)
print("Reduced shape:", reduced.shape)

/opt/anaconda3/envs/taxonomy_env/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Reduced shape: (43803, 25)

In [28]:
optics = OPTICS(
    min_samples=15,         
    metric="euclidean",
    cluster_method="xi",    
    xi=0.05,              
    min_cluster_size = 100
)

sample_df["C_id_optics"] = optics.fit_predict(reduced)

print("Clusters formed:", sample_df["C_id_optics"].nunique())
print(sample_df["C_id_optics"].value_counts().head(10))

Clusters formed: 179
C_id_optics
-1      20372
 64       361
 171      300
 168      220
 3        214
 146      205
 49       202
 61       195
 91       190
 11       185
Name: count, dtype: int64

In [30]:
ari = adjusted_rand_score(sample_df[LABEL_COL], sample_df["C_id_optics"])
nmi = normalized_mutual_info_score(sample_df[LABEL_COL], sample_df["C_id_optics"])

print("ARI:", round(ari, 4))
print("NMI:", round(nmi, 4))

ARI: 0.0121
NMI: 0.53

In [18]:
def cluster_purity(df, cluster_col, gold_col):
    stats = (
        df.groupby(cluster_col)[gold_col]
        .value_counts()
        .rename("count")
        .reset_index()
    )
    top = stats.groupby(cluster_col).first().reset_index()
    sizes = df[cluster_col].value_counts().rename("size").reset_index()
    merged = top.merge(sizes, on=cluster_col)
    merged["purity"] = merged["count"] / merged["size"]
    return merged.sort_values("purity", ascending=False)

purity_df = cluster_purity(sample_df, "C_id_optics", LABEL_COL)
purity_df.head(100)

     C_id_optics                                 Level3  count  size    purity
39            38                    Household Batteries    116   116  1.000000
46            45        Power Distribution Units (PDUs)    133   133  1.000000
142          141                        Projector Lamps    103   103  1.000000
51            50            Network Transceiver Modules    101   101  1.000000
73            72                        Mobile Headsets    106   106  1.000000
176          175                            Calculators    121   121  1.000000
170          169                 Flat Panel Spare Parts    105   105  1.000000
152          151                           Thin Clients    139   139  1.000000
80            79                        MP3/MP4 Players    107   107  1.000000
49            48             Power Adapters & Inverters    157   158  0.993671
112          111                Display Privacy Filters    129   130  0.992308
76            75                    DVD/Blu-Ray Players    119   120  0.991667
139          138                        Data Projectors    119   120  0.991667
47            46        Power Distribution Units (PDUs)    117   118  0.991525
110          109                             Mouse Pads    112   113  0.991150
145          144                     Projection Screens    108   109  0.990826
106          105                      Screen Protectors    104   105  0.990476
141          140                        Projector Lamps    152   154  0.987013
165          164                           Thin Clients    146   148  0.986486
61            60                          Print Servers    144   146  0.986301
175          174                            Calculators    133   135  0.985185
84            83                            Smartphones    129   131  0.984733
43            42  Uninterruptible Power Supplies (UPSs)    121   123  0.983740
82            81                          Mobile Phones    116   118  0.983051
156          155                      Operating Systems    115   117  0.982906
173          172                Display Privacy Filters    110   112  0.982143
136          135                       Projector Mounts    105   107  0.981308
167          166                     Fibre Optic Cables    157   160  0.981250
105          104                      Screen Protectors    104   106  0.981132
65            64                    Home Cinema Systems    102   104  0.980769
138          137                        Remote Controls    149   152  0.980263
72            71                        Mobile Headsets    191   195  0.979487
19            18                           Power Cables    110   113  0.973451
36            35                     Power Supply Units    110   113  0.973451
81            80                        MP3/MP4 Players    145   149  0.973154
151          150                            POS Systems    107   110  0.972727
53            52                       Network Switches    141   145  0.972414
114          113                              Keyboards    103   106  0.971698
109          108                                   Mice    374   385  0.971429
121          120                        Hospitality TVs    102   105  0.971429
168          167                                Servers    135   139  0.971223
52            51            Network Transceiver Modules    126   130  0.969231
177          176                           Fax Machines    123   127  0.968504
174          173                            Calculators    151   156  0.967949
178          177             Maintenance & Support Fees    115   119  0.966387
149          148            All-in-One PCs/Workstations    114   118  0.966102
146          145                            Dictaphones    126   131  0.961832
78            77                  Digital Media Players    114   119  0.957983
111          110                              Keyboards    105   110  0.954545
104          103                      Screen Protectors    164   172  0.953488
55            54               Network Media Converters    140   147  0.952381
32            31               Mobile Phone Spare Parts     95   100  0.950000
137          136                   Digital Photo Frames    104   110  0.945455
6              5                      Networking Cables    167   177  0.943503
140          139                        Data Projectors     97   103  0.941748
62            61                    Home Cinema Systems    112   119  0.941176
31            30                            Power Banks    143   152  0.940789
96            95                           Smartwatches    158   168  0.940476
83            82                          Mobile Phones    105   112  0.937500
162          161                                Servers    120   128  0.937500
134          133                       Projector Mounts    104   111  0.936937
69            68                        Home Audio Sets    101   108  0.935185
158          157            Antivirus Security Software    135   145  0.931034
2              1                           KVM Switches    130   140  0.928571
98            97                            Stylus Pens    103   111  0.927928
37            36                       Battery Chargers    137   148  0.925676
120          119                                    TVs    119   129  0.922481
77            76                    DVD/Blu-Ray Players    167   182  0.917582
99            98                                Holders    194   212  0.915094
75            74                    Home Cinema Systems    115   126  0.912698
166          165                     Fibre Optic Cables     93   102  0.911765
64            63                      Soundbar Speakers    122   134  0.910448
101          100                           Tablet Cases    111   122  0.909836
44            43                          UPS Batteries    108   119  0.907563
48            47  Uninterruptible Power Supplies (UPSs)     98   108  0.907407
30            29                 Mobile Device Chargers    107   118  0.906780
54            53                       Network Switches    102   113  0.902655
150          149                       PCs/Workstations    157   175  0.897143
160          159            Antivirus Security Software    139   155  0.896774
94            93                       Server Barebones    110   123  0.894309
95            94               PC/Workstation Barebones     92   103  0.893204
155          154          Warranty & Support Extensions    100   112  0.892857
17            16                             USB Cables     93   105  0.885714
60            59                       Network Antennas     88   100  0.880000
88            87               PC/Workstation Barebones     89   102  0.872549
42            41        Power Distribution Units (PDUs)    121   139  0.870504
93            92                       Server Barebones    103   120  0.858333
67            66                      Portable Speakers    112   131  0.854962
108          107                              Keyboards    131   154  0.850649
130          129                      Projection Lenses    129   152  0.848684
171          170             Software Licenses/Upgrades    156   184  0.847826
143          142                     Projection Screens     85   103  0.825243
34            33             Power Adapters & Inverters    120   146  0.821918
45            44  Uninterruptible Power Supplies (UPSs)     82   100  0.820000
35            34                     Power Supply Units     97   121  0.801653
38            37                    Household Batteries    107   134  0.798507
153          152          Warranty & Support Extensions     87   109  0.798165
122          121                      Computer Monitors     79   100  0.790000
1              0                           KVM Switches     98   125  0.784000
102          101                     Mobile Phone Cases     84   108  0.777778

In [36]:
example_cluster = sample_df["C_id_optics"].value_counts().index[4]

sample_df[sample_df["C_id_optics"] == example_cluster][["Brand", "ProductName", LABEL_COL]].head(100)

,Brand,ProductName,Level3
1271,APC,RBC59,Battery Chargers
1288,Approx,APPBC02,Battery Chargers
1371,Approx,APPBC01,Battery Chargers
1404,APC,Battery Management Harness,Battery Chargers
10271,APC,WBATTREPLC-G3-00,Installation Services
10352,APC,WBATTREPLC-SL-00,Installation Services
20129,APC,SBP10KHC3M1,Power Supply Units
20174,APC,SBP10KHR2M1,Power Supply Units
20197,APC,SYMMETRA BATTERY FRAME,Power Supply Units
20340,APC,SBP10KHR3M1,Power Supply Units
28094,2-Power,RBC55-C,UPS Batteries
28100,APC,SRT48RMBP,UPS Batteries
28101,APC,RBC124-OEM,UPS Batteries
28103,V7,RBC17-V7 UPS BATTERY FOR APC REPLACES APC # RBC 17,UPS Batteries
28104,APC,RBC48,UPS Batteries
28105,Tripp Lite,RBC96-3U,UPS Batteries
28107,APC,SRC96XLBP2S,UPS Batteries
28108,APC,RBC2-OEM,UPS Batteries
28109,APC,Battery Cartridge Replacement #17,UPS Batteries
28110,APC,WMBRS8-MB-T9B4,UPS Batteries
28117,APC,Battery 12V 76AH,UPS Batteries
28123,APC,RBC18,UPS Batteries
28125,V7,RBC132,UPS Batteries
28127,APC,XBP48RM1U-LI,UPS Batteries
28129,2-Power,RBC43,UPS Batteries
28131,APC,SURTA48XLBPJ,UPS Batteries
28133,APC,RBC8,UPS Batteries
28135,APC,SYBT2,UPS Batteries
28139,APC,Replacement Battery Cartridge #43,UPS Batteries
28141,V7,RBC116 UPS Replacement Battery for APC APCRBC116,UPS Batteries
28142,APC,RBC2,UPS Batteries
28145,V7,RBC24-V7 UPS BATTERY FOR APC REPLACES APC # RBC24,UPS Batteries
28148,APC,SYBT9-B4,UPS Batteries
28153,APC,SYBT9-B4LL,UPS Batteries
28155,APC,WMBRS10-MB-T9B6,UPS Batteries
28156,APC,APCRBC131,UPS Batteries
28163,APC,Replacement Battery Cartridge #10,UPS Batteries
28165,V7,RBC115 UPS Replacement Battery for APC APCRBC115,UPS Batteries
28166,APC,RBC20J,UPS Batteries
28175,APC,Replacement Battery Cartridge #21,UPS Batteries
28176,APC,Replacement Battery Cartridge #26,UPS Batteries
28177,APC,RBC34,UPS Batteries
28184,APC,APCRBC110,UPS Batteries
28185,APC,RBC114,UPS Batteries
28187,APC,APCRBC116,UPS Batteries
28189,APC,WMBRS18-MB-T9B4,UPS Batteries
28190,V7,RBC12-V7 UPS BATTERY FOR APC REPLACES APC # RBC12,UPS Batteries
28191,APC,RBC24J,UPS Batteries
28192,APC,RBC5J,UPS Batteries
28193,APC,RBC12,UPS Batteries
28201,APC,RBC44J,UPS Batteries
28208,APC,RBC48,UPS Batteries
28211,2-Power,RBC11,UPS Batteries
28220,V7,RBC48-V7 UPS BATTERY FOR APC REPLACES APC # RBC48,UPS Batteries
28221,APC,Replacement Battery Cartridge #9,UPS Batteries
28222,APC,RBC134,UPS Batteries
28223,APC,RBC24,UPS Batteries
28240,V7,APCRBC109,UPS Batteries
28241,APC,Replacement Battery Cartridge #57,UPS Batteries
28243,APC,RBC40,UPS Batteries
28244,APC,RBC110-OEM,UPS Batteries
28248,APC,RBC6,UPS Batteries
28253,APC,Replacement Battery Cartridge #18,UPS Batteries
28254,APC,RBC24,UPS Batteries
28255,APC,WMBRS13-MB-T9B6,UPS Batteries
28265,Salicru,UBT 12/7 Rechargeable AGM battery 7 Ah / 12 V,UPS Batteries
28269,Salicru,UBT 12/24 Rechargeable AGM battery 24 Ah / 12 V,UPS Batteries
28281,APC,RBC27-OEM,UPS Batteries
28286,APC,RBC22,UPS Batteries
28288,APC,RBC31-OEM,UPS Batteries
28293,APC,SRT72BP,UPS Batteries
28294,APC,SUA48RMXLBP3U,UPS Batteries
28295,2-Power,RBC48-C,UPS Batteries
28297,APC,RBC2,UPS Batteries
28303,APC,RBC109-OEM,UPS Batteries
28305,APC,SUA48XLBP,UPS Batteries
28306,APC,RBC33,UPS Batteries
28314,APC,RBC17,UPS Batteries
28318,APC,APCRBC143,UPS Batteries
28320,APC,RBC22-OEM,UPS Batteries
28321,APC,APCRBC113,UPS Batteries
28323,Salicru,UBT 12/9 Rechargeable AGM battery 9 Ah / 12 V,UPS Batteries
28330,APC,WMBRS16-MB-T9B6,UPS Batteries
28334,APC,RBC44EB,UPS Batteries
28340,APC,RBC32 OEM,UPS Batteries
28345,APC,RBC31,UPS Batteries
28346,APC,APCRBC123,UPS Batteries
28353,APC,RBC132,UPS Batteries
28354,APC,RBC154,UPS Batteries
28361,APC,RBC25-OEM,UPS Batteries
28363,APC,Replacement Battery Cartridge #3,UPS Batteries
28364,APC,RBC4,UPS Batteries
28365,APC,SYBT4,UPS Batteries
28369,APC,RBC23,UPS Batteries
28375,APC,RBC22,UPS Batteries
28378,APC,WMBRS8-MB-T9B6,UPS Batteries
28382,Tripp Lite,RBC7A,UPS Batteries
28384,APC,APCRBC124,UPS Batteries
28740,APC,Symmetra PX160 Battery Frame,Uninterruptible Power Supplies (UPSs)

In [34]:
example_cluster = sample_df["C_id_optics"].value_counts().index[14]

sample_df[sample_df["C_id_optics"] == example_cluster][["Brand", "ProductName", LABEL_COL]].head(100)

         Brand           ProductName                  Level3
7399   Samsung              WMN300SB  Flat Panel Wall Mounts
25668  Samsung            HW-M550/ZA       Soundbar Speakers
25675  Samsung               HW-H751       Soundbar Speakers
25678  Samsung             HW-J6501R       Soundbar Speakers
25683  Samsung            HW-K651/EN       Soundbar Speakers
25688  Samsung               HW-H551       Soundbar Speakers
25694  Samsung              HW-H7501       Soundbar Speakers
25697  Samsung              HW-J8501       Soundbar Speakers
25704    Sharp               HT-SL70       Soundbar Speakers
25708  Samsung             HW-J8501R       Soundbar Speakers
25718  Samsung               HW-K651       Soundbar Speakers
25720  Samsung            HW-K550/EN       Soundbar Speakers
25722  Toshiba               Mini 3D       Soundbar Speakers
25735  Samsung               HW-J651       Soundbar Speakers
25736  Toshiba            SB1 - SBK1       Soundbar Speakers
25741  Samsung               HW-N300       Soundbar Speakers
25746  Samsung               HW-H600       Soundbar Speakers
25748    Sharp               HT-SB60       Soundbar Speakers
25751  Samsung               HW-M360       Soundbar Speakers
25757  Samsung           HW-NW700/ZA       Soundbar Speakers
25759  Samsung               HW-F750       Soundbar Speakers
25761  Samsung            HW-H355/XN       Soundbar Speakers
25763  Toshiba  Mini 3D Sound Bar II       Soundbar Speakers
25770  Samsung            HW-Q70R/XU       Soundbar Speakers
25773  Samsung   4.1Ch 460W Soundbar       Soundbar Speakers
25777  Samsung               HW-C450       Soundbar Speakers
25778  Samsung            HW-H551/XU       Soundbar Speakers
25784  Samsung               HW-E551       Soundbar Speakers
25786    Sharp              HT-SB602       Soundbar Speakers
25788  Samsung             HW-J7501R       Soundbar Speakers
25790  Samsung               HW-D450       Soundbar Speakers
25795  Samsung             HW-J6501R       Soundbar Speakers
25802  Samsung               HW-Q60R       Soundbar Speakers
25805  Samsung            HW-M360/XN       Soundbar Speakers
25807  Samsung               HW-N950       Soundbar Speakers
25810  Samsung               HW-J550       Soundbar Speakers
25811  Samsung             HW-J6001R       Soundbar Speakers
25825  Samsung               HW-K550       Soundbar Speakers
25836  Samsung               HW-M550       Soundbar Speakers
25840  Samsung            HW-H450/ZF       Soundbar Speakers
25843  Samsung             HW-J6500R       Soundbar Speakers
25845  Samsung             HW-MS6500       Soundbar Speakers
25847  Samsung               HW-F355       Soundbar Speakers
25854  Toshiba               SBX1250       Soundbar Speakers
25855  Samsung               HW-Q90R       Soundbar Speakers
25858  Samsung              HW-MS651       Soundbar Speakers
25860  Samsung               HW-J650       Soundbar Speakers
25861  Samsung               HW-F450       Soundbar Speakers
25862  Samsung               HW-J470       Soundbar Speakers
25864  Samsung               HW-F850       Soundbar Speakers
25865  Samsung               HW-J355       Soundbar Speakers
25882  Samsung               HW-J551       Soundbar Speakers
25884  Samsung               HW-N450       Soundbar Speakers
25894  Samsung               HW-H750       Soundbar Speakers
25896  Samsung               HW-Q80R       Soundbar Speakers
25897  Samsung          SWA-9000S/ZA       Soundbar Speakers
25899  Samsung            HW-M360/ZA       Soundbar Speakers
25905  Samsung               HW-K551       Soundbar Speakers
25908  Samsung               HW-K335       Soundbar Speakers
25913  Samsung            HW-N300/XN       Soundbar Speakers
25914  Samsung               HW-F550       Soundbar Speakers
25915  Samsung               HW-F751       Soundbar Speakers
25918  Samsung       MS650 SOUND BAR       Soundbar Speakers
25919  Samsung              HW-H7500       Soundbar Speakers
25926  Samsung               HW-N650       Soundbar Speakers
25932  Samsung               HW-H355       Soundbar Speakers
25934  Samsung               HW-K650       Soundbar Speakers
25938  Samsung             HW-MS6501       Soundbar Speakers
25939  Samsung              HW-J8500       Soundbar Speakers
25940  Samsung               HW-H610       Soundbar Speakers
25943  Samsung               HW-K470       Soundbar Speakers
25945  Samsung              HW-MS550       Soundbar Speakers
25947  Samsung                  N850       Soundbar Speakers
25956    Sharp               HT-SL50       Soundbar Speakers
25959  Toshiba              SB3950E1       Soundbar Speakers
25966  Samsung              HW-NW700       Soundbar Speakers
26016  Samsung               HW-E551            Speaker Sets
26031  Samsung             SWA-9000S            Speaker Sets
26060  Samsung          SWA-9000S/XU            Speaker Sets

In [45]:
def cluster_quality(df, cluster_col, gold_col):
    stats = (
        df.groupby(cluster_col)[gold_col]
        .value_counts()
        .rename("count")
        .reset_index()
    )

    sizes = df[cluster_col].value_counts().rename("size").reset_index()
    merged = stats.merge(sizes, on=cluster_col)

    # purity
    top = (
        merged.sort_values("count", ascending=False)
        .groupby(cluster_col)
        .first()
        .reset_index()
    )
    top["purity"] = top["count"] / top["size"]
    top["impurity"] = 1 - top["purity"]

    # entropy
    entropy = (
        merged.assign(p=lambda x: x["count"] / x["size"])
        .groupby(cluster_col)
        .apply(lambda g: -np.sum(g["p"] * np.log(g["p"])))
        .reset_index(name="entropy")
    )

    return top.merge(entropy, on=cluster_col).sort_values("impurity", ascending=False)

In [46]:
quality_df = cluster_quality(sample_df, "C_id_agg", LABEL_COL)

# Worst clusters by impurity
quality_df.head(1000)

/var/folders/b_/cv34fjz13m34nzs9_x_gpp600000gn/T/ipykernel_50831/315832772.py:26: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: -np.sum(g["p"] * np.log(g["p"])))

,C_id_agg,Level3,count,size,purity,impurity,entropy
103,103,Keyboards,1,8,0.125000,0.875000,2.079442
133,133,Wire Connectors,1,7,0.142857,0.857143,1.945910
170,170,VGA Cables,268,1859,0.144164,0.855836,2.384614
39,39,DVD/Blu-Ray Players,298,1504,0.198138,0.801862,1.972885
76,76,Signage Displays,300,1494,0.200803,0.799197,1.635369
45,45,Flat Panel Desk Mounts,282,1304,0.216258,0.783742,1.823586
126,126,All-in-One PCs/Workstations,294,1335,0.220225,0.779775,1.752583
58,58,Server Barebones,300,1330,0.225564,0.774436,1.763303
5,5,Soundbar Speakers,298,1299,0.229407,0.770593,1.795150
42,42,Data Projectors,299,1283,0.233048,0.766952,1.713945
12,12,Audio Cables,295,1074,0.274674,0.725326,2.109096
27,27,Serial Attached SCSI (SAS) Cables,265,946,0.280127,0.719873,2.033273
37,37,Network Switches,296,990,0.298990,0.701010,1.377938
30,30,UPS Batteries,300,929,0.322928,0.677072,1.256790
28,28,Holders,1,3,0.333333,0.666667,1.098612
216,216,Cable Interface/Gender Adapters,4,12,0.333333,0.666667,1.357978
75,75,Tablet Cases,2,6,0.333333,0.666667,1.560710
19,19,Mobile Headsets,1,3,0.333333,0.666667,1.098612
135,135,Mobile Device Chargers,14,40,0.350000,0.650000,1.597532
59,59,IT Support Services,185,517,0.357834,0.642166,1.338222
197,197,Fibre Optic Cables,291,804,0.361940,0.638060,1.375907
26,26,Mobile Phone Cases,10,27,0.370370,0.629630,1.467076
11,11,Mobile Phone Cables,6,16,0.375000,0.625000,1.808046
60,60,Power Banks,284,757,0.375165,0.624835,1.185016
51,51,Wireless Routers,295,764,0.386126,0.613874,1.228183
57,57,Wire Connectors,4,10,0.400000,0.600000,1.193550
47,47,Handheld Device Accessories,4,10,0.400000,0.600000,1.609438
85,85,Mobile Phone Cases,4,10,0.400000,0.600000,1.279854
107,107,Network Switch Components,4,10,0.400000,0.600000,1.418484
145,145,Holders,2,5,0.400000,0.600000,1.332179
80,80,Flat Panel Accessories,2,5,0.400000,0.600000,1.332179
254,254,Handheld Device Accessories,5,12,0.416667,0.583333,1.539654
167,167,Wire Connectors,5,12,0.416667,0.583333,1.352209
253,253,Video Cable Adapters,3,7,0.428571,0.571429,1.277034
0,0,Flat Panel Mount Accessories,3,7,0.428571,0.571429,1.277034
100,100,Mobile Device Dock Stations,7,16,0.437500,0.562500,1.628620
7,7,Keyboards,292,667,0.437781,0.562219,1.102895
15,15,USB Cables,266,606,0.438944,0.561056,1.241136
2,2,POS Systems,23,52,0.442308,0.557692,1.205100
165,165,Flat Panel Floor Stands,5,11,0.454545,0.545455,1.240684
25,25,Wire Connectors,5,11,0.454545,0.545455,1.366711
89,89,Power Adapters & Inverters,284,584,0.486301,0.513699,1.011611
46,46,Office Suites,90,181,0.497238,0.502762,0.986938
99,99,Handheld Device Accessories,2,4,0.500000,0.500000,1.039721
18,18,Handheld Device Accessories,1,2,0.500000,0.500000,0.693147
62,62,Tablet Cases,1,2,0.500000,0.500000,0.693147
228,228,Input Device Accessories,3,6,0.500000,0.500000,1.242453
188,188,Flat Panel Wall Mounts,8,16,0.500000,0.500000,0.881532
130,130,Mobile Phone Cases,6,12,0.500000,0.500000,1.198849
68,68,Installation Services,3,6,0.500000,0.500000,1.011404
223,223,Handheld Device Accessories,1,2,0.500000,0.500000,0.693147
246,246,Screen Protectors,1,2,0.500000,0.500000,0.693147
235,235,Handheld Device Accessories,1,2,0.500000,0.500000,0.693147
93,93,Mobile Device Chargers,1,2,0.500000,0.500000,0.693147
127,127,Handheld Device Accessories,2,4,0.500000,0.500000,1.039721
97,97,Mouse Pads,1,2,0.500000,0.500000,0.693147
219,219,Flat Panel Mount Accessories,1,2,0.500000,0.500000,0.693147
63,63,KVM Switches,280,557,0.502693,0.497307,0.908509
16,16,Mobile Phones,292,571,0.511384,0.488616,0.790622
81,81,Handheld Device Accessories,21,40,0.525000,0.475000,1.147508
194,194,Flat Panel Spare Parts,295,543,0.543278,0.456722,1.105098
90,90,Hardware Firewalls,110,201,0.547264,0.452736,0.876704
83,83,Remote Controls,5,9,0.555556,0.444444,0.936888
34,34,Stylus Pens,13,23,0.565217,0.434783,1.033233
61,61,Antivirus Security Software,289,509,0.567780,0.432220,0.825062
70,70,MP3/MP4 Player Cases,8,14,0.571429,0.428571,0.876006
109,109,Network Media Converters,4,7,0.571429,0.428571,1.153742
77,77,Digital Media Players,24,41,0.585366,0.414634,1.360954
40,40,Power Cables,261,441,0.591837,0.408163,0.938431
124,124,Smartwatches,187,312,0.599359,0.400641,0.755785
220,220,Battery Chargers,3,5,0.600000,0.400000,0.673012
214,214,Coaxial Cables,3,5,0.600000,0.400000,0.950271
49,49,Power Adapters & Inverters,3,5,0.600000,0.400000,0.950271
22,22,Tablet Cases,270,443,0.609481,0.390519,0.867351
172,172,Smartphones,25,41,0.609756,0.390244,0.668857
41,41,Maintenance & Support Fees,115,183,0.628415,0.371585,0.813433
3,3,Mice,299,474,0.630802,0.369198,0.730494
1,1,Mobile Device Chargers,7,11,0.636364,0.363636,0.655482
125,125,Serial Attached SCSI (SAS) Cables,9,14,0.642857,0.357143,0.651757
178,178,Warranty & Support Extensions,31,47,0.659574,0.340426,0.641317
72,72,Handheld Device Accessories,2,3,0.666667,0.333333,0.636514
55,55,Installation Services,2,3,0.666667,0.333333,0.636514
141,141,Warranty & Support Extensions,2,3,0.666667,0.333333,0.636514
222,222,Patch Panels,2,3,0.666667,0.333333,0.636514
33,33,Handheld Device Accessories,2,3,0.666667,0.333333,0.636514
117,117,Handheld Device Accessories,2,3,0.666667,0.333333,0.636514
203,203,Loudspeakers,2,3,0.666667,0.333333,0.636514
184,184,Power Adapters & Inverters,2,3,0.666667,0.333333,0.636514
50,50,KVM Cables,8,12,0.666667,0.333333,0.823959
173,173,Video Cable Adapters,2,3,0.666667,0.333333,0.636514
166,166,Network Transceiver Modules,4,6,0.666667,0.333333,0.636514
67,67,Handheld Device Accessories,16,23,0.695652,0.304348,0.856859
71,71,Flat Panel Accessories,7,10,0.700000,0.300000,0.801819
183,183,Loudspeakers,7,10,0.700000,0.300000,0.801819
120,120,Flat Panel Floor Stands,103,146,0.705479,0.294521,1.066045
44,44,Mobile Device Dock Stations,107,151,0.708609,0.291391,1.087613
242,242,Antivirus Security Software,10,14,0.714286,0.285714,0.598270
140,140,AV Extenders,29,40,0.725000,0.275000,0.824660
98,98,Installation Services,47,63,0.746032,0.253968,0.734669
151,151,Internal Power Cables,3,4,0.750000,0.250000,0.562335
24,24,Cable Interface/Gender Adapters,3,4,0.750000,0.250000,0.562335
142,142,Handheld Device Accessories,3,4,0.750000,0.250000,0.562335
8,8,Video Converters,9,12,0.750000,0.250000,0.721464
112,112,Handheld Device Accessories,19,25,0.760000,0.240000,0.659215
144,144,IT Support Services,88,114,0.771930,0.228070,0.610945
204,204,Holders,49,63,0.777778,0.222222,0.795321
86,86,Operating Systems,33,42,0.785714,0.214286,0.666095
38,38,Smartwatches,11,14,0.785714,0.214286,0.519580
238,238,Tablets,4,5,0.800000,0.200000,0.500402
122,122,Tablet Cases,4,5,0.800000,0.200000,0.500402
66,66,Software Licenses/Upgrades,9,11,0.818182,0.181818,0.600166
153,153,Installation Services,9,11,0.818182,0.181818,0.600166
146,146,Mobile Phone Cases,5,6,0.833333,0.166667,0.450561
54,54,Projector Accessories,10,12,0.833333,0.166667,0.566086
229,229,Flat Panel Accessories,10,12,0.833333,0.166667,0.450561
160,160,Power Supply Units,5,6,0.833333,0.166667,0.450561
9,9,Portable Speakers,37,44,0.840909,0.159091,0.641324
179,179,Maintenance & Support Fees,6,7,0.857143,0.142857,0.410116
180,180,Input Device Accessories,6,7,0.857143,0.142857,0.410116
31,31,Handheld Device Accessories,6,7,0.857143,0.142857,0.410116
32,32,Flat Panel Wall Mounts,7,8,0.875000,0.125000,0.376770
6,6,Holders,112,127,0.881890,0.118110,0.363143
92,92,Projection Lenses,132,149,0.885906,0.114094,0.396316
225,225,Operating Systems,8,9,0.888889,0.111111,0.348832
230,230,Flat Panel Accessories,8,9,0.888889,0.111111,0.348832
20,20,Projector Accessories,8,9,0.888889,0.111111,0.348832
23,23,Projector Accessories,44,49,0.897959,0.102041,0.329544
198,198,Input Device Accessories,10,11,0.909091,0.090909,0.304636
114,114,Cable Interface/Gender Adapters,10,11,0.909091,0.090909,0.304636
73,73,Household Batteries,297,323,0.919505,0.080495,0.341619
10,10,Battery Chargers,46,50,0.920000,0.080000,0.361947
118,118,Holders,74,79,0.936709,0.063291,0.235929
48,48,MP3/MP4 Player Cases,216,229,0.943231,0.056769,0.280020
113,113,Mobile Phone Cases,17,18,0.944444,0.055556,0.214559
91,91,Wire Connectors,80,84,0.952381,0.047619,0.191444
79,79,Display Privacy Filters,300,315,0.952381,0.047619,0.191444
36,36,Flat Panel Accessories,22,23,0.956522,0.043478,0.178845
101,101,Mobile Phone Spare Parts,272,284,0.957746,0.042254,0.187161
84,84,Stylus Pens,277,289,0.958478,0.041522,0.207507
52,52,Radios,281,293,0.959044,0.040956,0.212392
17,17,Digital Photo Frames,119,123,0.967480,0.032520,0.143397
29,29,Dictaphones,126,130,0.969231,0.030769,0.158734
4,4,Mobile Phone Cases,231,238,0.970588,0.029412,0.170251
14,14,Remote Controls,253,258,0.980620,0.019380,0.116060
53,53,Print Servers,147,149,0.986577,0.013423,0.071195
88,88,Projector Lamps,299,303,0.986799,0.013201,0.070242
177,177,Fax Machines,124,125,0.992000,0.008000,0.046594
21,21,Screen Protectors,279,281,0.992883,0.007117,0.042289
13,13,Mobile Headsets,295,297,0.993266,0.006734,0.040385
199,199,Keyboards,1,1,1.000000,0.000000,-0.000000
207,207,Mobile Phone Cables,1,1,1.000000,0.000000,-0.000000
208,208,Patch Panels,25,25,1.000000,0.000000,-0.000000
209,209,Patch Panels,1,1,1.000000,0.000000,-0.000000
202,202,Soundbar Speakers,1,1,1.000000,0.000000,-0.000000
206,206,Network Antennas,1,1,1.000000,0.000000,-0.000000
201,201,Flat Panel Accessories,1,1,1.000000,0.000000,-0.000000
195,195,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
200,200,Calculators,299,299,1.000000,0.000000,-0.000000
196,196,Mobile Phone Cables,2,2,1.000000,0.000000,-0.000000
210,210,Projector Accessories,1,1,1.000000,0.000000,-0.000000
205,205,Mobile Phone Spare Parts,1,1,1.000000,0.000000,-0.000000
243,243,Remote Controls,1,1,1.000000,0.000000,-0.000000
211,211,Battery Chargers,1,1,1.000000,0.000000,-0.000000
212,212,Stylus Pens,3,3,1.000000,0.000000,-0.000000
255,255,Embedded Computers,1,1,1.000000,0.000000,-0.000000
252,252,Installation Services,1,1,1.000000,0.000000,-0.000000
251,251,Flat Panel Desk Mounts,1,1,1.000000,0.000000,-0.000000
250,250,Wire Connectors,9,9,1.000000,0.000000,-0.000000
249,249,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
248,248,Maintenance & Support Fees,2,2,1.000000,0.000000,-0.000000
247,247,Wire Connectors,1,1,1.000000,0.000000,-0.000000
245,245,Power Cables,3,3,1.000000,0.000000,-0.000000
244,244,Computer Monitors,1,1,1.000000,0.000000,-0.000000
192,192,Keyboards,1,1,1.000000,0.000000,-0.000000
241,241,Software Licenses/Upgrades,66,66,1.000000,0.000000,-0.000000
240,240,Household Batteries,1,1,1.000000,0.000000,-0.000000
239,239,MP3/MP4 Player Cases,1,1,1.000000,0.000000,-0.000000
237,237,WLAN Access Points,4,4,1.000000,0.000000,-0.000000
236,236,Operating Systems,3,3,1.000000,0.000000,-0.000000
234,234,Mobile Phones,1,1,1.000000,0.000000,-0.000000
233,233,Mobile Device Chargers,1,1,1.000000,0.000000,-0.000000
232,232,Projector Accessories,1,1,1.000000,0.000000,-0.000000
231,231,Mobile Phone Spare Parts,1,1,1.000000,0.000000,-0.000000
227,227,Warranty & Support Extensions,11,11,1.000000,0.000000,-0.000000
226,226,VGA Cables,1,1,1.000000,0.000000,-0.000000
224,224,Serial Attached SCSI (SAS) Cables,1,1,1.000000,0.000000,-0.000000
221,221,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
218,218,Network Switch Components,1,1,1.000000,0.000000,-0.000000
217,217,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
215,215,Flat Panel Desk Mounts,1,1,1.000000,0.000000,-0.000000
213,213,Battery Chargers,1,1,1.000000,0.000000,-0.000000
193,193,Maintenance & Support Fees,2,2,1.000000,0.000000,-0.000000
128,128,Mouse Pads,1,1,1.000000,0.000000,-0.000000
191,191,Mobile Headsets,1,1,1.000000,0.000000,-0.000000
190,190,Keyboards,1,1,1.000000,0.000000,-0.000000
134,134,Mobile Phones,1,1,1.000000,0.000000,-0.000000
132,132,Mobile Device Keyboards,1,1,1.000000,0.000000,-0.000000
131,131,Flat Panel Wall Mounts,1,1,1.000000,0.000000,-0.000000
129,129,Embedded Computers,1,1,1.000000,0.000000,-0.000000
123,123,Remote Controls,8,8,1.000000,0.000000,-0.000000
121,121,Software Licenses/Upgrades,2,2,1.000000,0.000000,-0.000000
119,119,Warranty & Support Extensions,1,1,1.000000,0.000000,-0.000000
116,116,Remote Controls,1,1,1.000000,0.000000,-0.000000
115,115,Remote Controls,2,2,1.000000,0.000000,-0.000000
111,111,Computer Monitors,2,2,1.000000,0.000000,-0.000000
110,110,AV Extenders,21,21,1.000000,0.000000,-0.000000
108,108,InfiniBand Cables,4,4,1.000000,0.000000,-0.000000
106,106,Stylus Pens,2,2,1.000000,0.000000,-0.000000
105,105,MP3/MP4 Players,5,5,1.000000,0.000000,-0.000000
104,104,Remote Controls,1,1,1.000000,0.000000,-0.000000
102,102,Software Licenses/Upgrades,1,1,1.000000,0.000000,-0.000000
96,96,Software Licenses/Upgrades,2,2,1.000000,0.000000,-0.000000
95,95,Radios,1,1,1.000000,0.000000,-0.000000
94,94,Remote Controls,2,2,1.000000,0.000000,-0.000000
87,87,Battery Chargers,2,2,1.000000,0.000000,-0.000000
82,82,Operating Systems,143,143,1.000000,0.000000,-0.000000
78,78,Remote Controls,3,3,1.000000,0.000000,-0.000000
74,74,Cable Interface/Gender Adapters,12,12,1.000000,0.000000,-0.000000
69,69,Handheld Device Accessories,2,2,1.000000,0.000000,-0.000000
65,65,Operating Systems,28,28,1.000000,0.000000,-0.000000
64,64,Holders,2,2,1.000000,0.000000,-0.000000
56,56,Network Antennas,127,127,1.000000,0.000000,-0.000000
43,43,Remote Controls,9,9,1.000000,0.000000,-0.000000
35,35,Handheld Device Accessories,3,3,1.000000,0.000000,-0.000000
136,136,Internal Power Cables,1,1,1.000000,0.000000,-0.000000
137,137,Cable Interface/Gender Adapters,1,1,1.000000,0.000000,-0.000000
138,138,Flat Panel Accessories,1,1,1.000000,0.000000,-0.000000
163,163,Holders,7,7,1.000000,0.000000,-0.000000
189,189,Calculators,1,1,1.000000,0.000000,-0.000000
187,187,Wire Connectors,1,1,1.000000,0.000000,-0.000000
186,186,Handheld Device Accessories,6,6,1.000000,0.000000,-0.000000
185,185,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
182,182,Holders,1,1,1.000000,0.000000,-0.000000
181,181,Software Licenses/Upgrades,2,2,1.000000,0.000000,-0.000000
176,176,Operating Systems,1,1,1.000000,0.000000,-0.000000
175,175,IT Support Services,1,1,1.000000,0.000000,-0.000000
174,174,Mouse Pads,1,1,1.000000,0.000000,-0.000000
171,171,Installation Services,1,1,1.000000,0.000000,-0.000000
169,169,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
168,168,Holders,1,1,1.000000,0.000000,-0.000000
164,164,Warranty & Support Extensions,1,1,1.000000,0.000000,-0.000000
162,162,Servers,1,1,1.000000,0.000000,-0.000000
139,139,Installation Services,1,1,1.000000,0.000000,-0.000000
161,161,Maintenance & Support Fees,1,1,1.000000,0.000000,-0.000000
159,159,Flat Panel Accessories,1,1,1.000000,0.000000,-0.000000
158,158,Holders,2,2,1.000000,0.000000,-0.000000
157,157,Battery Chargers,1,1,1.000000,0.000000,-0.000000
156,156,Screen Protectors,1,1,1.000000,0.000000,-0.000000
155,155,Operating Systems,1,1,1.000000,0.000000,-0.000000
154,154,Remote Controls,1,1,1.000000,0.000000,-0.000000
152,152,Operating Systems,2,2,1.000000,0.000000,-0.000000
150,150,Tablets,1,1,1.000000,0.000000,-0.000000
149,149,Installation Services,1,1,1.000000,0.000000,-0.000000
148,148,Handheld Device Accessories,2,2,1.000000,0.000000,-0.000000
147,147,Handheld Device Accessories,3,3,1.000000,0.000000,-0.000000
143,143,Warranty & Support Extensions,1,1,1.000000,0.000000,-0.000000
256,256,Flat Panel Wall Mounts,4,4,1.000000,0.000000,-0.000000

In [29]:
example_cluster = sample_df["C_id_agg"].value_counts().index[49]

sample_df[sample_df["C_id_agg"] == example_cluster][["Brand", "ProductName", LABEL_COL]].head(1000)

,Brand,ProductName,Level3
5697,Samsung,MID-UD55MB,Flat Panel Accessories
5703,Salora,Neck P32AT2BXHS7850,Flat Panel Accessories
5705,NEC,SP-4615,Flat Panel Accessories
5717,Salora,Stand Left P15ATGT16L00H,Flat Panel Accessories
5724,Salora,Stand P15ATBDAHG19400000H,Flat Panel Accessories
5732,Salora,Stand Right (P15ATBDAHG6665RD000H),Flat Panel Accessories
5738,NEC,SP-5220,Flat Panel Accessories
5742,NEC,SP-32,Flat Panel Accessories
5743,Samsung,MID40-UX3,Flat Panel Accessories
5745,Samsung,MID462-UT2,Flat Panel Accessories
5748,NEC,SP4020-4620,Flat Panel Accessories
5759,Salora,Stand Left P15ATBDAHB2032L000H,Flat Panel Accessories
5761,Salora,Neck P23AT407851,Flat Panel Accessories
5763,Salora,Stand Right P15ATBDAHB2032R000H,Flat Panel Accessories
5767,Samsung,MID-UX46MB,Flat Panel Accessories
5768,Salora,Stand (P23ATU05921HX),Flat Panel Accessories
5776,Salora,Stand Left (P23AT322552),Flat Panel Accessories
5777,NEC,SP-6520,Flat Panel Accessories
5791,Salora,Stand Right P15ATGT16R00H,Flat Panel Accessories
5806,Samsung,MID-UD55FS,Flat Panel Accessories
5807,NEC,LCD6520LSP,Flat Panel Accessories
5810,Samsung,MID46-UX3,Flat Panel Accessories
5811,NEC,SP-PS52,Flat Panel Accessories
5812,NEC,SP-M40B,Flat Panel Accessories
5815,Salora,Stand Left P15ATBDAHC1824L000H,Flat Panel Accessories
5818,Salora,Stand Right P15ATBDAHC1824R000H,Flat Panel Accessories
5824,Salora,Stand P23AT398372,Flat Panel Accessories
5826,Salora,Stand Right (P23AT322554),Flat Panel Accessories
5827,Salora,Neck P15ATB.DZH-G193200-0H,Flat Panel Accessories
5832,Salora,Neck Right (P30ATMR240301),Flat Panel Accessories
5838,Salora,Stand (P32AT2HDB6727),Flat Panel Accessories
5864,Salora,Stand Left (P15ATBDAHG6665LD000H),Flat Panel Accessories
5865,Salora,Stand P15ATB.DAH-G1932000-2H,Flat Panel Accessories
5868,Salora,Neck Left (P30ATM240301),Flat Panel Accessories
5879,3M,Contour Flange bezel for CT150 touch monitor,Flat Panel Accessories
5883,Salora,Neck SET (P23ATM67705),Flat Panel Accessories
5886,Salora,Stand Right P15ATBDA0C1932R000H,Flat Panel Accessories
6712,Dell Wyse,575-BBFN,Flat Panel Mount Accessories
6793,Samsung,MID-UX40MB,Flat Panel Mount Accessories
7015,Samsung,SBB-NTBSB,Flat Panel Spare Parts
19757,Salora,AV Cable P2TAT609402001,Power Cables
21398,NEC,Stand for VT46/460/560/660,Projector Accessories
25846,NEC,Soundbar 90,Soundbar Speakers

In [35]:
sample_df[sample_df["C_id_"] == 49][["Brand", "ProductName", LABEL_COL]].head(1000)

KeyError: 'C_id_agg'

In [47]:
sample_df[sample_df["C_id_agg"] == 49][["Brand", "ProductName", LABEL_COL]].nunique()

Brand          3
ProductName    5
Level3         3
dtype: int64

In [60]:
sample_df[sample_df["C_id_agg"] == 200][["Brand", "ProductName", LABEL_COL]].nunique()

Brand            4
ProductName    267
Level3           1
dtype: int64

In [51]:
sample_df[sample_df["C_id_agg"] == 200][["Brand", "ProductName", LABEL_COL]].head(100)

      Brand        ProductName       Level3
1921  Casio            MS-20NC  Calculators
1922  Sharp            EL-243S  Calculators
1923  Canon              F-604  Calculators
1924     HP                12c  Calculators
1925  Sharp           EL-339HB  Calculators
1926  Casio           SL-100NC  Calculators
1927  Casio        JW-200TV-RD  Calculators
1928  Sharp         EL-531XGVL  Calculators
1929  Sharp           EL-334FB  Calculators
1930     HP             10bII+  Calculators
1931     HP               40gs  Calculators
1932  Casio            SL-450L  Calculators
1933  Sharp          EL-2607PG  Calculators
1934  Casio            DR-T220  Calculators
1935  Sharp         EL-501XBWH  Calculators
1936  Sharp        EL-2630PIII  Calculators
1937  Casio          MS-8VERII  Calculators
1938  Canon         HS-1200TCG  Calculators
1939  Casio           SL-300NC  Calculators
1940  Casio            FX-82ES  Calculators
1941  Casio              HL-4A  Calculators
1942  Canon           MP120-MG  Calculators
1943  Canon           MP11DX-2  Calculators
1944  Sharp           EL-1750V  Calculators
1945  Sharp          EL-338GGY  Calculators
1946  Casio  Classwiz FX-350EX  Calculators
1947     HP     OfficeCalc 200  Calculators
1948  Sharp           EL-233SB  Calculators
1949  Canon     MP120-MG-es II  Calculators
1950  Casio      fx-991LA PLUS  Calculators
1951     HP              300s+  Calculators
1952  Canon            MP25-MG  Calculators
1953  Sharp        EL-W531XHGR  Calculators
1954  Casio      FX-115ES Plus  Calculators
1955  Casio       FX-85DE Plus  Calculators
1956  Casio           SL-300NC  Calculators
1957  Casio        SL-300NC-GN  Calculators
1958  Casio             MS-6NC  Calculators
1959  Casio           WD-320MT  Calculators
1960  Canon             F-720I  Calculators
1961  Casio            MS-300M  Calculators
1962  Canon           X MARK 1  Calculators
1963  Canon           LS-120PC  Calculators
1964  Sharp           EL-W211G  Calculators
1965  Sharp           EL-509XB  Calculators
1966  Casio            HR-8RCE  Calculators
1967  Canon             AS-120  Calculators
1968  Canon               F710  Calculators
1969  Sharp           EL-W200E  Calculators
1970  Casio           MS-88ECO  Calculators
1971  Canon        P1-DTSC HWB  Calculators
1972  Sharp           EL-243EB  Calculators
1973  Sharp           EL-1611P  Calculators
1974     HP         Quick Calc  Calculators
1975  Casio            HL-815L  Calculators
1976  Casio         SL-310TER+  Calculators
1977  Casio       SL-1000SC-BK  Calculators
1978  Canon            P170-DH  Calculators
1979     HP         Quick Calc  Calculators
1980  Canon           P23-DH V  Calculators
1981  Sharp       EL-W506XB-YL  Calculators
1982  Casio             MS-20S  Calculators
1983  Casio             MS-7UC  Calculators
1984  Casio       SL-1000SC-BU  Calculators
1985  Casio         MS-20UC-YG  Calculators
1986  Sharp         EL-R297BBK  Calculators
1987  Casio           DH-12TER  Calculators
1988  Casio            FX-82EX  Calculators
1989  Canon            LS-123k  Calculators
1990  Sharp           EL-1611V  Calculators
1991  Sharp           EL-520WB  Calculators
1992  Casio           MS-100MS  Calculators
1993  Canon           BP36-LTS  Calculators
1994     HP              Prime  Calculators
1995  Casio        JW-200SC-BK  Calculators
1996  Canon         TS-1200TCG  Calculators
1997  Sharp  EL M332 BBL - BLU  Calculators
1998  Canon          AS-2200RI  Calculators
1999  Sharp            EL-250S  Calculators
2000  Casio         FX-9860GII  Calculators
2001  Canon            LS-83TC  Calculators
2002  Casio        SL-310UC-GN  Calculators
2003     HP                12c  Calculators
2004  Canon           LS-103TC  Calculators
2005  Casio       ClassPad 330  Calculators
2006  Canon           BP-36LTS  Calculators
2007  Casio          SL-1100TV  Calculators
2008  Canon             F-502G  Calculators
2009  Canon             LS-82Z  Calculators
2010  Sharp           EL-501XB  Calculators
2011  Casio             KL-120  Calculators
2012  Casio              MS-8B  Calculators
2013  Sharp           EL-330ER  Calculators
2014  Sharp            EL-143S  Calculators
2015  Canon           MP120-MG  Calculators
2016  Casio          HR-150TEC  Calculators
2017     HP       EasyCalc 100  Calculators
2018  Sharp          EL-2901RH  Calculators
2019  Casio             HS8VER  Calculators
2020  Canon            F-715SG  Calculators

In [ ]:
sample_df["Level3"].head(2)