In [1]:
import os, random
import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from umap import UMAP
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

INPUT_CSV = "/Users/suyashmali/Case_Study_Materials/LLM/Notebook/Cleaned_Data_1.csv"
TEXT_COL = "metadata_clean"
LABEL_COL = "Level3"

MIN_SAMPLES = 100
MAX_SAMPLES = 500

EMBED_MODEL = "all-mpnet-base-v2"

/opt/anaconda3/envs/taxonomy_env/lib/python3.10/site-packages/google/api_core/_python_version_support.py:266: FutureWarning: You are using a Python version (3.10.18) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)

In [2]:
df = pd.read_csv(INPUT_CSV)

def min_max_sample(df, label_col, min_k, max_k, seed=42):
    sampled_groups = []
    for label, g in df.groupby(label_col):
        if len(g) < min_k:
            continue
        n = min(len(g), max_k)
        sampled_groups.append(g.sample(n=n, random_state=seed))
    return pd.concat(sampled_groups).reset_index(drop=True)

sample_df = min_max_sample(df, LABEL_COL, MIN_SAMPLES, MAX_SAMPLES)

print("Final sample size:", len(sample_df))
print("Unique Level3 categories:", sample_df[LABEL_COL].nunique())

print(sample_df[[LABEL_COL]].value_counts().head(25))

Final sample size: 43803
Unique Level3 categories: 126
Level3
Wireless Routers                   500
Power Banks                        500
Network Switches                   500
Projector Mounts                   500
Projector Lamps                    500
Household Batteries                500
IT Support Services                500
Projector Accessories              500
Projection Screens                 500
Power Supply Units                 500
Power Distribution Units (PDUs)    500
Power Cables                       500
KVM Switches                       500
Keyboards                          500
Power Adapters & Inverters         500
Flat Panel Spare Parts             500
Portable Speakers                  500
PCs/Workstations                   500
Mice                               500
Mobile Device Chargers             500
PC/Workstation Barebones           500
Mobile Device Keyboards            500
Mobile Headsets                    500
Notebooks                          500
Mobile Phone Cases                 500
Name: count, dtype: int64

In [3]:
sample_df.columns

Index(['Brand', 'BrandPartCode', 'ProductName', 'Description.LongProductName',
       'Description.LongDesc', 'SummaryDescription.LongSummaryDescription',
       'pathlist_names', 'Level1', 'Level2', 'Level3', 'metadata_text',
       'metadata_clean'],
      dtype='object')

In [4]:
# sample_df[sample_df["ProductName"] == "C30"][["metadata_clean", "pathlist_names"]]

In [5]:
print(sample_df[[LABEL_COL]].value_counts().head(130))

Level3
Wireless Routers                  500
Power Banks                       500
Network Switches                  500
Projector Mounts                  500
Projector Lamps                   500
                                 ...
Portable Stereo Systems           108
Composite Video Cables            106
Component (YPbPr) Video Cables    104
Mobile Phone Cables               103
Input Device Accessories          100
Name: count, Length: 126, dtype: int64

In [6]:
sample_df["final_text"] = (
    sample_df[TEXT_COL]
    .fillna("")
    .astype(str)
    .str.strip()
)

fallback_cols = ["ProductName", "Title", "SummaryDescription.LongSummaryDescription"]

def fallback_text(row):
    if row["final_text"]:
        return row["final_text"]
    return " ".join(
        str(row[c]) for c in fallback_cols
        if c in row and pd.notna(row[c])
    )

sample_df["final_text"] = sample_df.apply(fallback_text, axis=1)

print("Non-empty texts:", sample_df["final_text"].astype(bool).sum())

Non-empty texts: 43803

In [7]:
sample_df[TEXT_COL].head(1)

0    vertiv ems1000t, avocent. type av transmitter,...
Name: metadata_clean, dtype: object

In [8]:
sample_df["final_text"].head(1)

0    vertiv ems1000t, avocent. type av transmitter,...
Name: final_text, dtype: object

In [9]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option("max_colwidth", None)

In [11]:
model = SentenceTransformer(EMBED_MODEL)

embeddings = model.encode(
    sample_df["final_text"].tolist(),
    batch_size=128,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/343 [00:00<?, ?it/s]

In [11]:
umap_model = UMAP(
    n_neighbors=15,
    min_dist=0.0,
    n_components=25,
    metric="cosine",
    random_state=RANDOM_STATE
)

reduced = umap_model.fit_transform(embeddings)
print("Reduced shape:", reduced.shape)

/opt/anaconda3/envs/taxonomy_env/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Reduced shape: (43803, 25)

In [13]:
# from sklearn.cluster import AgglomerativeClustering
# from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

# thresholds = [0.5, 0.55, 0.6]

# results = []

# for t in thresholds:
#     agg = AgglomerativeClustering(
#         n_clusters=None,
#         distance_threshold=t,
#         linkage="average",
#         metric="cosine"
#     )
    
#     labels = agg.fit_predict(embeddings)
    
#     n_clusters = len(set(labels))
#     ari = adjusted_rand_score(sample_df[LABEL_COL], labels)
#     nmi = normalized_mutual_info_score(sample_df[LABEL_COL], labels)
    
#     results.append((t, n_clusters, ari, nmi))
    
#     print(
#         f"threshold={t:<5} | clusters={n_clusters:<4} | "
#         f"ARI={ari:.4f} | NMI={nmi:.4f}"
#     )

In [20]:
# sample_df.head()

In [12]:
sample_df['C_id_agg'] = labels  # from threshold=0.5
sample_df['C_id_agg'].value_counts().describe()

count     209.000000
mean      209.583732
std       577.307272
min         1.000000
25%         2.000000
50%         7.000000
75%        67.000000
max      5099.000000
Name: count, dtype: float64

In [13]:
# sample_df['C_id_agg'].nunique()

In [14]:
# sample_df[sample_df["C_id_agg"] == example_cluster][["Brand", "ProductName", LABEL_COL]].head(10)

In [15]:
sample_df.columns

Index(['Brand', 'BrandPartCode', 'ProductName', 'Description.LongProductName',
       'Description.LongDesc', 'SummaryDescription.LongSummaryDescription',
       'pathlist_names', 'Level1', 'Level2', 'Level3', 'metadata_text',
       'metadata_clean', 'final_text', 'C_id_agg'],
      dtype='object')

In [16]:
# cluster = sample_df['C_id_agg'].value_counts().index[99] 
# print("Inspecting HDBSCAN cluster:", cluster)
# display_cols = ['Brand', 'ProductName', 'metadata_clean', 'Level3', 'C_id_agg']
# display(sample_df[sample_df['C_id_agg'] == cluster][display_cols].head(100))

In [17]:
sample_df[sample_df['C_id_agg'] == 45][['Brand', 'ProductName', 'metadata_clean', 'Level3', 'C_id_agg']].nunique()

Brand             2
ProductName       4
metadata_clean    4
Level3            2
C_id_agg          1
dtype: int64

In [14]:
agg = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=0.5,
    linkage="average",
    metric="cosine"
)

sample_df["C_id_agg"] = agg.fit_predict(embeddings)

print("Clusters formed:", sample_df["C_id_agg"].nunique())
print(sample_df["C_id_agg"].value_counts().head(10))

In [42]:
ari = adjusted_rand_score(sample_df[LABEL_COL], sample_df["C_id_agg"])
nmi = normalized_mutual_info_score(sample_df[LABEL_COL], sample_df["C_id_agg"])

print("ARI:", round(ari, 4))
print("NMI:", round(nmi, 4))

ARI: 0.3777
NMI: 0.8024

In [19]:
def cluster_purity(df, cluster_col, gold_col):
    stats = (
        df.groupby(cluster_col)[gold_col]
        .value_counts()
        .rename("count")
        .reset_index()
    )
    top = stats.groupby(cluster_col).first().reset_index()
    sizes = df[cluster_col].value_counts().rename("size").reset_index()
    merged = top.merge(sizes, on=cluster_col)
    merged["purity"] = merged["count"] / merged["size"]
    return merged.sort_values("purity", ascending=False)

purity_df = cluster_purity(sample_df, "C_id_agg", LABEL_COL)
purity_df.head(10)

     C_id_agg                      Level3  count  size  purity
208       208   Network Switch Components      1     1     1.0
167       167         E-Book Reader Cases      1     1     1.0
111       111  Software Licenses/Upgrades      1     1     1.0
108       108                Patch Panels      1     1     1.0
107       107            Battery Chargers      1     1     1.0
106       106               Wired Routers      1     1     1.0
161       161                 Calculators      1     1     1.0
1           1  Software Licenses/Upgrades      6     6     1.0
101       101           InfiniBand Cables      5     5     1.0
162       162                     Servers      1     1     1.0

In [18]:
example_cluster = sample_df["C_id_agg"].value_counts().index[4]

sample_df[sample_df["C_id_agg"] == example_cluster][["Brand", "ProductName", LABEL_COL]].head(100)

,Brand,ProductName,Level3
78,Philips,Bluetooth® Hi-Fi adapter AEA2500/12,AV Extenders
1675,ZAGG,IFZ-AU-AX-RED,Audio Cables
2873,Philips,LFH9034,Cable Interface/Gender Adapters
6781,Philips,docking speaker with Bluetooth® AD530/12,Docking Speakers
6785,Philips,docking speaker AD333/05,Docking Speakers
6786,Philips,Micro music system DCM3155/12,Docking Speakers
6787,V7,SP5500-BT-WHT-9NC,Docking Speakers
6788,Philips,wireless speaker dock AS860/10,Docking Speakers
6790,Samsung,ESP-70,Docking Speakers
6791,Philips,docking speaker with Bluetooth® DS7530/12,Docking Speakers
6792,Samsung,DA-E651,Docking Speakers
6793,Philips,docking speaker with Bluetooth® DS3480/12,Docking Speakers
6794,Philips,docking speaker AD713/12,Docking Speakers
6795,Logitech,Pure-Fi Express Plus,Docking Speakers
6796,Samsung,DA-E650,Docking Speakers
6797,Philips,docking speaker DS1150/12,Docking Speakers
6799,Philips,Primo docking speaker DS9/10,Docking Speakers
6800,Logitech,S125i,Docking Speakers
6801,Philips,docking speaker DS3400/12,Docking Speakers
6802,Samsung,DA-E750,Docking Speakers
6804,Philips,docking speaker AD315/05,Docking Speakers
6808,Logitech,Pure-Fi Express Plus,Docking Speakers
6809,Sony,NWD300 Active speaker,Docking Speakers
6810,Philips,CD Soundmachine AZD102/12,Docking Speakers
6812,Philips,DCM250/12,Docking Speakers
6814,Samsung,DA-E550,Docking Speakers
6815,Logitech,S715i,Docking Speakers
6816,Logitech,980-000596,Docking Speakers
6817,Sony,RDH-GTK37iP,Docking Speakers
6818,Approx,appSP07B,Docking Speakers
6819,Philips,wireless speaker dock AS360/12,Docking Speakers
6820,Philips,DC185,Docking Speakers
6821,LG,CM2820DAB,Docking Speakers
6822,Sony,RDP-XF300iP,Docking Speakers
6823,Logitech,Pure-Fi Anywhere,Docking Speakers
6824,Philips,DC199 Docking Entertainment System,Docking Speakers
6825,Logitech,s500,Docking Speakers
6826,Philips,docking speaker with Bluetooth® DS3500/12,Docking Speakers
6827,Sony,RDP-X30iP,Docking Speakers
6828,Philips,docking speaker DS6100/10,Docking Speakers
6829,Logitech,S135i,Docking Speakers
6830,Philips,DC199B/12,Docking Speakers
6831,Philips,docking speaker DS3120/05,Docking Speakers
6833,Philips,docking speaker DS7580/10,Docking Speakers
6834,Philips,docking sound system DTM5096/12,Docking Speakers
6835,Sony,RDP-V20iPB,Docking Speakers
6836,Philips,DTM9030/10,Docking Speakers
6837,Sony,CMT-FX300I,Docking Speakers
6838,Sony,RDP-M7iP,Docking Speakers
6839,Philips,docking speaker DS1155/98,Docking Speakers
6843,Logitech,S125i,Docking Speakers
6844,Philips,docking speaker DS7510/12,Docking Speakers
6846,Sony,RDP-M7IPN,Docking Speakers
6847,Philips,docking speaker DS1400/05,Docking Speakers
6848,Philips,docking speaker with Bluetooth® AS111/98,Docking Speakers
6849,Logitech,mm50 Portable Speakers for iPod,Docking Speakers
6850,Philips,docking speaker with Bluetooth® DS7700/12,Docking Speakers
6851,Philips,DS1100/12,Docking Speakers
6852,Philips,docking entertainment system DCM129/12,Docking Speakers
6853,Philips,SBA1600 Portable Speaker System,Docking Speakers
6854,Logitech,MM32 Portable Speakers for iPod,Docking Speakers
6855,Philips,Original radio mini ORD2105B/12,Docking Speakers
6856,Philips,Clock radio for iPod/ iPhone AJ3275D/12,Docking Speakers
6858,LG,CM2820,Docking Speakers
6859,Philips,docking speaker with Bluetooth® AS851/10,Docking Speakers
6860,Philips,SBD7000 Speaker Dock,Docking Speakers
6861,Philips,docking speaker DS3205/12,Docking Speakers
6862,Philips,CD Soundmachine AZD1755/12,Docking Speakers
6863,Logitech,"Pure-Fi Anywhere, White",Docking Speakers
6864,Philips,docking speaker with Bluetooth® AD533/05,Docking Speakers
6865,Philips,docking speaker AD315/12,Docking Speakers
6866,Philips,docking speaker with Bluetooth® AD530/05,Docking Speakers
6867,Sony,ICF-DS15iP,Docking Speakers
6869,Philips,Docking station with Bluetooth® DTB297/10,Docking Speakers
6870,Philips,MP3 portable speaker SBA3000/00,Docking Speakers
6871,Sony,RDP-XF300iPN,Docking Speakers
6873,Philips,Micro music system DCM2055/12,Docking Speakers
6875,Samsung,ECR-A1A2BE,Docking Speakers
6877,Sony,RDP-V20iPW,Docking Speakers
6878,Philips,iBoom JukeBox DLA78405/10,Docking Speakers
6879,Philips,SoundCurve wireless speaker DS8800W/10,Docking Speakers
6880,Denver,SP-5,Docking Speakers
6881,Philips,TCI360/12,Docking Speakers
6883,Philips,Portable Speaker System SBP1100/00,Docking Speakers
6884,Samsung,DA-E650,Docking Speakers
6885,Philips,SoundSphere mini docking speakers DS6600/10,Docking Speakers
6886,Philips,docking speaker DS3110/37,Docking Speakers
6888,Samsung,Portable Bluetooth Speaker,Docking Speakers
6889,LG,ND1530,Docking Speakers
6890,Philips,Alarm Clock radio for iPod/iPhone AJ5300D/37,Docking Speakers
6891,Samsung,DA-E750,Docking Speakers
6892,Philips,docking station for iPod/iPhone AJ7040D/12,Docking Speakers
6893,Philips,docking speaker DS8550/10,Docking Speakers
6894,Philips,Micro music system DTM3155/12,Docking Speakers
6895,Philips,docking speaker DS3205/05,Docking Speakers
6896,ASUS,SP-BT23,Docking Speakers
6897,Philips,Original radio ORD7300/10,Docking Speakers
6898,Logitech,980-000597,Docking Speakers
6899,Philips,docking music system DCM5090/10,Docking Speakers
6900,Logitech,Pure-Fi Elite,Docking Speakers

In [19]:
example_cluster = sample_df["C_id_agg"].value_counts().index[14]

sample_df[sample_df["C_id_agg"] == example_cluster][["Brand", "ProductName", LABEL_COL]].head(1000)

,Brand,ProductName,Level3
8116,Chief,HB71P,Flat Panel Ceiling Mounts
8159,Vogel's,VPRO ceiling mount,Flat Panel Ceiling Mounts
8160,Chief,RPA034,Flat Panel Ceiling Mounts
8161,Vogel's,PFA 9015 B,Flat Panel Ceiling Mounts
8162,Chief,RPA181,Flat Panel Ceiling Mounts
8180,Vogel's,VPRO PFA9020 ceiling mount,Flat Panel Ceiling Mounts
8189,Sony,Mounting coupling for pendant applications SNCA-CEILING,Flat Panel Ceiling Mounts
8206,Chief,KITPF018024,Flat Panel Ceiling Mounts
8215,Chief,HB93C,Flat Panel Ceiling Mounts
8226,Newstar,FPMA-C100,Flat Panel Ceiling Mounts
8231,Chief,SLB148,Flat Panel Ceiling Mounts
8240,Chief,CMS115 Ceiling Plate,Flat Panel Ceiling Mounts
8251,Chief,Suspended Ceiling Tile Replacement Kit,Flat Panel Ceiling Mounts
8253,Chief,CMS445 Ceiling Tile Replacement Kit,Flat Panel Ceiling Mounts
8255,NEC,MP300CM,Flat Panel Ceiling Mounts
8256,Vogel's,PPC 110,Flat Panel Ceiling Mounts
8261,Sony,Ceiling Bracket,Flat Panel Ceiling Mounts
8265,Chief,Heavy Duty Ceiling Mount,Flat Panel Ceiling Mounts
8270,Sony,Optional anti-theft ceiling mount kit,Flat Panel Ceiling Mounts
8273,Newstar,FPMA-C200D,Flat Panel Ceiling Mounts
8284,Chief,CMS492,Flat Panel Ceiling Mounts
8285,Chief,RPMBU,Flat Panel Ceiling Mounts
8289,Chief,RPA171,Flat Panel Ceiling Mounts
8296,Philips,LCD/Plasma Ceiling Support,Flat Panel Ceiling Mounts
8305,Chief,Suspended Ceiling Kit,Flat Panel Ceiling Mounts
8306,Sony,CHSMCS,Flat Panel Ceiling Mounts
8862,Vogel's,VPRO PFA9016 Extension tube,Flat Panel Floor Stands
9163,Chief,SLB195,Flat Panel Mount Accessories
9166,Chief,CPAE030W,Flat Panel Mount Accessories
9173,Chief,CMA106,Flat Panel Mount Accessories
9188,Chief,KITLS012018,Flat Panel Mount Accessories
9195,Chief,SSB293,Flat Panel Mount Accessories
9219,Chief,SLB223,Flat Panel Mount Accessories
9223,Chief,VCM91C,Flat Panel Mount Accessories
9269,Chief,CMS390,Flat Panel Mount Accessories
9271,Chief,SLB284,Flat Panel Mount Accessories
9278,Chief,CMS006009S,Flat Panel Mount Accessories
9292,Chief,SA1,Flat Panel Mount Accessories
9301,Chief,CMA151,Flat Panel Mount Accessories
9305,Chief,VCM Interface Bracket,Flat Panel Mount Accessories
9314,Chief,CPA263,Flat Panel Mount Accessories
9327,Chief,CMS0709W,Flat Panel Mount Accessories
9342,Chief,CMA365,Flat Panel Mount Accessories
9367,Chief,SSB315,Flat Panel Mount Accessories
9384,Newstar,Ceiling mount cover for FPMA-C100 & FPMA-C100SILVER (50 mm diameter) - White,Flat Panel Mount Accessories
9386,Chief,CMS009012W,Flat Panel Mount Accessories
9390,Chief,SLB279,Flat Panel Mount Accessories
9394,Chief,CMS012018S,Flat Panel Mount Accessories
9396,NEC,AEC012018,Flat Panel Mount Accessories
9408,Chief,CMS018S,Flat Panel Mount Accessories
9409,Chief,SLB193,Flat Panel Mount Accessories
9417,Chief,SLB176,Flat Panel Mount Accessories
9418,Chief,SSBU,Flat Panel Mount Accessories
9426,Chief,HB016E,Flat Panel Mount Accessories
9428,Chief,CPA262,Flat Panel Mount Accessories
9430,Chief,CPAE300W,Flat Panel Mount Accessories
9479,Chief,SLM191,Flat Panel Mount Accessories
9498,NEC,AEC0203,Flat Panel Mount Accessories
10137,Chief,WPAU,Flat Panel Wall Mounts
10169,DELL,725-10019,Flat Panel Wall Mounts
10224,Chief,CMS003W,Flat Panel Wall Mounts
10230,Vogel's,PPC 110,Flat Panel Wall Mounts
10274,Sony,UNIPMA1,Flat Panel Wall Mounts
10366,Vogel's,VPW 565,Flat Panel Wall Mounts
10401,Vogel's,PPC 130,Flat Panel Wall Mounts
10407,Vogel's,PPC 280,Flat Panel Wall Mounts
10429,Chief,CMS006W,Flat Panel Wall Mounts
10437,Sony,PLP91/D,Flat Panel Wall Mounts
29252,Chief,AN2BA100,Projection Screens
29581,Chief,CPA036,Projector Accessories
29582,Chief,CMSI,Projector Accessories
29602,HP,xp7000 Ceiling Mount Kit,Projector Accessories
29607,Chief,SLM317,Projector Accessories
29608,Chief,SLM034,Projector Accessories
29618,B-Tech,BT7894,Projector Accessories
29619,Projecta,"Mounting kit - Cinelpro Electrol/Cinelpro RF Electrol, 300 см",Projector Accessories
29635,Chief,SLM266,Projector Accessories
29638,Chief,SLM278,Projector Accessories
29656,Chief,SLM181,Projector Accessories
29661,Chief,CPA365,Projector Accessories
29669,Vogel's,PPC 180 Projector ceiling support,Projector Accessories
29670,Chief,SSB085,Projector Accessories
29677,NEC,LT30CM,Projector Accessories
29683,Chief,SLB249,Projector Accessories
29686,Chief,Heavy Duty LCD/CRT Projector Ceiling Mount,Projector Accessories
29688,Chief,WMAL106,Projector Accessories
29705,NEC,NP06CM,Projector Accessories
29706,Chief,SLM286,Projector Accessories
29722,Chief,SLM301,Projector Accessories
29723,NEC,NP05UCM,Projector Accessories
29733,Chief,CMS440N,Projector Accessories
29739,Projecta,"Mounting kit - Cinelpro Electrol/Cinelpro RF Electrol, 240 см",Projector Accessories
29741,Chief,SLB091,Projector Accessories
29747,Chief,SLM178,Projector Accessories
29748,Sony,PSS-610,Projector Accessories
29759,Chief,PL2C,Projector Accessories
29770,Chief,SLM298,Projector Accessories
29772,Chief,NAV1,Projector Accessories
29781,Chief,SLM085,Projector Accessories
29788,Vogel's,Projector Ceiling Support,Projector Accessories
29789,Chief,CMS490,Projector Accessories
29796,Chief,SLB218,Projector Accessories
29797,Chief,SLM280,Projector Accessories
29801,Vogel's,PPA301 Projector Anti-Theft Housing,Projector Accessories
29802,Chief,CPAE150B,Projector Accessories
29808,Projecta,Pro-Lift Pivot 65,Projector Accessories
29809,NEC,NP03WM,Projector Accessories
29820,Vogel's,PPS 350,Projector Accessories
29826,Epson,V12H893020,Projector Accessories
29831,Chief,SLB257,Projector Accessories
29835,NEC,NP05CM Ceiling mount f NP1000/2000,Projector Accessories
29843,Chief,SLB173,Projector Accessories
29847,Vogel's,PPC 150 Projector Support,Projector Accessories
29848,Chief,SLM293,Projector Accessories
29853,Chief,SLM284,Projector Accessories
29863,Vogel's,PPS 800,Projector Accessories
29872,Chief,SLB146,Projector Accessories
29876,Sony,Celing mounth security,Projector Accessories
29877,Chief,SLB216,Projector Accessories
29880,Chief,SLB317,Projector Accessories
29881,Chief,NAV2,Projector Accessories
29882,NEC,NP01UCM,Projector Accessories
29884,Chief,SLM023,Projector Accessories
29891,Chief,RPMA1W,Projector Accessories
29894,Vogel's,PPA 301 Projector Anti-Theft Housing,Projector Accessories
29895,Vogel's,PPS 350 Short throw projector mount,Projector Accessories
29901,NEC,NP07CM,Projector Accessories
29916,Sony,PSS-AT7,Projector Accessories
29920,Chief,SLM186,Projector Accessories
29928,Chief,SLB292,Projector Accessories
29931,Chief,SLM315,Projector Accessories
29932,Chief,SLB276,Projector Accessories
29946,NEC,NP09CM,Projector Accessories
29951,Chief,SLM246,Projector Accessories
29960,DELL,725-BBBE,Projector Accessories
29961,Chief,SLM316,Projector Accessories
29962,Chief,SLB181,Projector Accessories
29963,Chief,SLM168,Projector Accessories
29972,Vogel's,VPW 565 Projector Wall Support,Projector Accessories
29974,Chief,SLB208,Projector Accessories
29975,Chief,SLM196,Projector Accessories
29977,NEC,NP03CM,Projector Accessories
29982,Vogel's,PPW 100 Projector Support,Projector Accessories
29983,Chief,PL2B,Projector Accessories
29986,Chief,SLM273,Projector Accessories
29994,Projecta,"Mounting kit - Cinelpro Electrol/Cinelpro RF Electrol, 200 см",Projector Accessories
30007,Vogel's,PPL 7575,Projector Accessories
30012,Chief,CPAE030B,Projector Accessories
30024,Chief,CPAE300B,Projector Accessories
30032,Chief,SLB081,Projector Accessories
30036,Chief,UMA152,Projector Accessories
30044,Chief,SLM228,Projector Accessories
30060,Chief,SLB316,Projector Accessories
30071,Chief,SLM251,Projector Accessories
30578,Chief,HB012R,Projector Mount Accessories
30579,NEC,PJ01FPA,Projector Mount Accessories
30580,Chief,SSB145,Projector Mount Accessories
30581,Chief,CMA640B,Projector Mount Accessories
30582,Chief,CMS048,Projector Mount Accessories
30583,Chief,SSB176,Projector Mount Accessories
30584,Chief,SSM027,Projector Mount Accessories
30585,Chief,Pin Connection Coupler,Projector Mount Accessories
30586,Chief,SSM176,Projector Mount Accessories
30587,Chief,SMA602,Projector Mount Accessories
30588,Chief,SLB232,Projector Mount Accessories
30589,Chief,SLB303,Projector Mount Accessories
30590,Chief,CMA278,Projector Mount Accessories
30591,Chief,CMS060,Projector Mount Accessories
30592,Chief,SLB304,Projector Mount Accessories
30593,Chief,SSM198,Projector Mount Accessories
30594,Chief,CMS0608,Projector Mount Accessories
30595,Chief,SSM261,Projector Mount Accessories
30596,Chief,CMS0203,Projector Mount Accessories
30597,Chief,SSM171,Projector Mount Accessories
30598,Chief,SLB085,Projector Mount Accessories
30599,Chief,SSM263,Projector Mount Accessories
30600,TooQ,PJ1010EXT45-B,Projector Mount Accessories
30601,Chief,SLB358,Projector Mount Accessories
30602,Chief,CMS009012,Projector Mount Accessories
30603,Chief,CMA351,Projector Mount Accessories
30604,Chief,CMA330-G,Projector Mount Accessories
30605,Chief,SSB287,Projector Mount Accessories
30606,Chief,CMS012018,Projector Mount Accessories
30607,Chief,SLB349,Projector Mount Accessories
30608,Projecta,Pre-Installation Box,Projector Mount Accessories
30609,NEC,SCP200,Projector Mount Accessories
30610,Chief,SLM311,Projector Mount Accessories
30611,Chief,SSB232,Projector Mount Accessories
30612,Chief,SSM287,Projector Mount Accessories
30613,Chief,Truss Clamp,Projector Mount Accessories
30614,Chief,SLB364,Projector Mount Accessories
30615,Chief,SSMUW,Projector Mount Accessories
30616,Chief,CMS0406,Projector Mount Accessories
30617,Chief,RPAB1W,Projector Mount Accessories
30618,Chief,SLM245,Projector Mount Accessories
30619,Chief,CMS0608W,Projector Mount Accessories
30620,Chief,SSB313,Projector Mount Accessories
30621,Chief,SLM145,Projector Mount Accessories
30622,Chief,SLB353,Projector Mount Accessories
30623,Chief,SSB278,Projector Mount Accessories
30624,Chief,HB49E,Projector Mount Accessories
30625,Chief,SSM311,Projector Mount Accessories
30626,Chief,SLB228,Projector Mount Accessories
30627,Chief,PG3AW,Projector Mount Accessories
30628,Chief,CMA348,Projector Mount Accessories
30629,Chief,CPA640,Projector Mount Accessories
30630,Chief,SSM178,Projector Mount Accessories
30631,Epson,V12H777020,Projector Mount Accessories
30632,Chief,SLB321,Projector Mount Accessories
30634,Chief,CMA395-G,Projector Mount Accessories
30635,Chief,CMS012,Projector Mount Accessories
30636,Chief,SSM093,Projector Mount Accessories
30637,Chief,CMA270,Projector Mount Accessories
30638,Chief,SSB198,Projector Mount Accessories
30639,Chief,CMSZ006,Projector Mount Accessories
30640,Chief,SSM186,Projector Mount Accessories
30641,Chief,WBAUF1,Projector Mount Accessories
30642,Chief,SLM352,Projector Mount Accessories
30643,Chief,SSB191,Projector Mount Accessories
30644,C2G,16280,Projector Mount Accessories
30645,Chief,CMS006009,Projector Mount Accessories
30647,Chief,SSB163,Projector Mount Accessories
30648,Chief,PG1AW,Projector Mount Accessories
30649,Chief,PG2AW,Projector Mount Accessories
30650,Chief,HB74P,Projector Mount Accessories
30651,Chief,SLB178,Projector Mount Accessories
30652,Chief,SSB203,Projector Mount Accessories
30653,Chief,SSM145,Projector Mount Accessories
30654,Chief,LPK1,Projector Mount Accessories
30655,Chief,SSB257,Projector Mount Accessories
30656,Chief,WMAC16,Projector Mount Accessories
30657,Chief,SSB302,Projector Mount Accessories
30658,Chief,SLM3131,Projector Mount Accessories
30659,Chief,SSB284,Projector Mount Accessories
30660,Chief,SSB280,Projector Mount Accessories
30661,Chief,CMS036,Projector Mount Accessories
30662,Chief,HB026S,Projector Mount Accessories
30663,Chief,SSM163,Projector Mount Accessories
30664,Chief,SLB267,Projector Mount Accessories
30665,Chief,SLB307,Projector Mount Accessories
30666,Chief,SSBUW,Projector Mount Accessories
30667,Chief,SSB266,Projector Mount Accessories
30668,Chief,SSB093,Projector Mount Accessories
30669,Chief,SLM341,Projector Mount Accessories
30670,Chief,SSB173,Projector Mount Accessories
30671,Chief,SSM245,Projector Mount Accessories
30672,Chief,SSM191,Projector Mount Accessories
30673,Chief,SSM318,Projector Mount Accessories
30674,Chief,SSM232,Projector Mount Accessories
30675,Chief,SSM166,Projector Mount Accessories
30676,Chief,CMSZ006S,Projector Mount Accessories
30677,Chief,Zubehör Projektoren,Projector Mount Accessories
30678,Chief,SLB357,Projector Mount Accessories
30679,Chief,SSB259,Projector Mount Accessories
30680,Chief,SSM168,Projector Mount Accessories
30681,Chief,SSM085,Projector Mount Accessories
30682,Chief,CMS012018W,Projector Mount Accessories
30683,Sony,PAM600,Projector Mount Accessories
30684,Chief,HB44E,Projector Mount Accessories
30686,Chief,RPA343,Projector Mount Accessories
30687,Chief,SSB279,Projector Mount Accessories
30688,Chief,SSB308,Projector Mount Accessories
30689,Chief,SLB280,Projector Mount Accessories
30690,Chief,CPAE080S,Projector Mount Accessories
30691,Chief,SSB186,Projector Mount Accessories
30692,Chief,CMS018W,Projector Mount Accessories
30693,Chief,SSM193,Projector Mount Accessories
30694,Chief,HB94C,Projector Mount Accessories
30695,Chief,HB52D,Projector Mount Accessories
30696,Chief,SLB334,Projector Mount Accessories
30697,Chief,SSM283,Projector Mount Accessories
30698,Chief,SLB246,Projector Mount Accessories
30699,Chief,SLB352,Projector Mount Accessories
30700,Chief,CMA110-G,Projector Mount Accessories
30701,Chief,SSM181,Projector Mount Accessories
30702,Chief,SSB303,Projector Mount Accessories
30703,Chief,RPA000S,Projector Mount Accessories
30704,Chief,HB42E,Projector Mount Accessories
30705,Chief,SLM358,Projector Mount Accessories
30706,Chief,SSM023,Projector Mount Accessories
30707,Chief,SSM278,Projector Mount Accessories
30708,Chief,RSA000W,Projector Mount Accessories
30709,Chief,SLB311,Projector Mount Accessories
30710,Chief,SLB324,Projector Mount Accessories
30711,Chief,HB92C,Projector Mount Accessories
30712,Chief,SLB268,Projector Mount Accessories
30714,Chief,SSB283,Projector Mount Accessories
30715,Chief,SSM173,Projector Mount Accessories
30716,Chief,CPAE150S,Projector Mount Accessories
30717,Chief,SLM345,Projector Mount Accessories
30718,Chief,RPAC1,Projector Mount Accessories
30719,Chief,CMSFAN,Projector Mount Accessories
30721,Chief,SLM356,Projector Mount Accessories
30722,Chief,SLBLEGW,Projector Mount Accessories
30723,Chief,SLB344,Projector Mount Accessories
30724,Chief,CMA275,Projector Mount Accessories
30725,Sony,PAM-1.5M,Projector Mount Accessories
30726,Chief,SLB260,Projector Mount Accessories
30727,Chief,CMS0507,Projector Mount Accessories
30728,Chief,SSB221,Projector Mount Accessories
30729,Chief,SLM354,Projector Mount Accessories
30730,Chief,SSM3131,Projector Mount Accessories
30732,Chief,SMA620,Projector Mount Accessories
30733,Chief,CPAE080,Projector Mount Accessories
30734,Chief,SLM361,Projector Mount Accessories
30735,Chief,CPA640W,Projector Mount Accessories
30736,Chief,SSB020,Projector Mount Accessories
30737,Chief,SSB261,Projector Mount Accessories
30738,Chief,SLB287,Projector Mount Accessories
30739,Chief,SSM221,Projector Mount Accessories
30740,Chief,SSM273,Projector Mount Accessories
30741,NEC,AE022020,Projector Mount Accessories
30742,Chief,CMS060W,Projector Mount Accessories
30743,Chief,SSB178,Projector Mount Accessories
30744,Chief,SLB336,Projector Mount Accessories
30745,Chief,SLB341,Projector Mount Accessories
30746,Chief,SSB3131,Projector Mount Accessories
30747,Chief,HB010R,Projector Mount Accessories
30748,Chief,SSB251,Projector Mount Accessories
30749,Chief,SSB027,Projector Mount Accessories
30750,Chief,SLBU,Projector Mount Accessories
30751,Chief,SSB181,Projector Mount Accessories
30754,Chief,SSMUS,Projector Mount Accessories
30755,Chief,SLM304,Projector Mount Accessories
30756,Chief,LCDPA,Projector Mount Accessories
30757,Chief,SLM357,Projector Mount Accessories
30758,Chief,PG1A,Projector Mount Accessories
30759,Chief,SLBUW,Projector Mount Accessories
30760,Chief,SLM260,Projector Mount Accessories
30761,Chief,HB47E,Projector Mount Accessories
30762,Chief,Pin Connection Column 30 cm,Projector Mount Accessories
30763,Chief,SLM291,Projector Mount Accessories
30764,Chief,CMS012W,Projector Mount Accessories
30765,Chief,SLB339,Projector Mount Accessories
30766,Chief,CMS1012,Projector Mount Accessories
30767,Chief,"Pin Connection Column 24""",Projector Mount Accessories
30768,Chief,SLB351,Projector Mount Accessories
30769,Chief,SLB360,Projector Mount Accessories
30770,Chief,SSB196,Projector Mount Accessories
30772,Chief,SSM228,Projector Mount Accessories
30773,Chief,CMS261W,Projector Mount Accessories
30775,Chief,SLM344,Projector Mount Accessories
30776,Chief,SLB312,Projector Mount Accessories
30778,Techly,ICA-PM-1603M,Projector Mounts
30779,Chief,RPA316,Projector Mounts
30780,Chief,RSMC020,Projector Mounts
30782,NEC,NP70CM,Projector Mounts
30783,Chief,RPMC261,Projector Mounts
30785,Chief,HB100B,Projector Mounts
30786,Chief,RSA145,Projector Mounts
30787,Techly,Professional Projector Ceiling Stand Extension 110-197cm ICA-PM 104XL,Projector Mounts
30788,Chief,RPMB193,Projector Mounts
30789,Chief,KITEP030045W,Projector Mounts
30790,Chief,RPMC259,Projector Mounts
30791,Chief,RSMB273,Projector Mounts
30792,Chief,RSMD285,Projector Mounts
30793,Chief,CMS492CP2,Projector Mounts
30794,Chief,RPMC308,Projector Mounts
30795,Chief,RSMB166,Projector Mounts
30796,C2G,16279,Projector Mounts
30797,Sony,PAM200,Projector Mounts
30798,Chief,RPA041,Projector Mounts
30799,Chief,KITAF009012S,Projector Mounts
30801,Chief,RPMB313,Projector Mounts
30802,Chief,KITPA018024,Projector Mounts
30803,B-Tech,BT884-M,Projector Mounts
30804,Chief,RPMB268,Projector Mounts
30805,Chief,RPMB259,Projector Mounts
30806,Chief,RPMB232,Projector Mounts
30808,Chief,RPMC091,Projector Mounts
30809,Chief,RPA257,Projector Mounts
30810,Chief,RSMD232,Projector Mounts
30811,Chief,RSMB163,Projector Mounts
30812,Chief,RPMA302,Projector Mounts
30813,Chief,RSA085,Projector Mounts
30814,Chief,RSMC251,Projector Mounts
30815,Techly,ICA-PM-200WH,Projector Mounts
30816,Chief,RPMC191,Projector Mounts
30817,Chief,RPMA260,Projector Mounts
30818,NEC,NP05WK,Projector Mounts
30820,Chief,KITPS012018,Projector Mounts
30821,Vogel's,PPL 7575,Projector Mounts
30823,NEC,AEC006009,Projector Mounts
30824,AISENS,CP02TSRE-051,Projector Mounts
30825,Chief,RSMA181,Projector Mounts
30827,Chief,RPMA267,Projector Mounts
30828,Chief,CMA700W,Projector Mounts
30829,Chief,Projector Ceiling Mount Kit,Projector Mounts
30830,Vogel's,Universal Projector Mount,Projector Mounts
30831,Chief,RPMA195,Projector Mounts
30832,Chief,RSMD196,Projector Mounts
30833,Chief,LCD2C,Projector Mounts
30834,Chief,SL236SPI,Projector Mounts
30835,B-Tech,BT5890-075,Projector Mounts
30836,Chief,RPMC023,Projector Mounts
30837,Chief,RPMB163,Projector Mounts
30838,Chief,RSMA280,Projector Mounts
30839,Chief,RPMB279,Projector Mounts
30840,Chief,CMA700,Projector Mounts
30841,AISENS,CWP01TSE-049,Projector Mounts
30842,Chief,RPMC297,Projector Mounts
30843,Chief,RSMA302,Projector Mounts
30844,Chief,RSMA245,Projector Mounts
30845,Chief,RSMA273,Projector Mounts
30846,Chief,RPA026,Projector Mounts
30847,Chief,RSMEU,Projector Mounts
30848,Chief,CMA385,Projector Mounts
30849,Chief,SL236SP,Projector Mounts
30850,Chief,RSA181,Projector Mounts
30851,Chief,RPMC163,Projector Mounts
30852,Chief,KITES006W,Projector Mounts
30853,Chief,RSA258,Projector Mounts
30854,Chief,RSMCUW,Projector Mounts
30855,Chief,RSMAUS,Projector Mounts
30856,Chief,RSMA251,Projector Mounts
30857,Chief,RSMD257,Projector Mounts
30859,Chief,RSMB171,Projector Mounts
30860,Chief,RSMA089,Projector Mounts
30861,Chief,RSMC257,Projector Mounts
30862,NEC,PJ03WHM,Projector Mounts
30863,Vogel's,PPSA 100 Wall lock,Projector Mounts
30864,TooQ,PJ2012T-B,Projector Mounts
30865,Chief,RSMA261,Projector Mounts
30866,Chief,RSMB259,Projector Mounts
30867,Chief,RPMC301,Projector Mounts
30868,Chief,RPMB195,Projector Mounts
30869,Chief,WM120S,Projector Mounts
30870,Chief,RPA227,Projector Mounts
30871,Chief,RSMD093,Projector Mounts
30872,Tripp Lite,Full Motion Universal Ceiling Mount for Projectors,Projector Mounts
30873,Chief,RPMC168,Projector Mounts

In [21]:
def cluster_quality(df, cluster_col, gold_col):
    stats = (
        df.groupby(cluster_col)[gold_col]
        .value_counts()
        .rename("count")
        .reset_index()
    )

    sizes = df[cluster_col].value_counts().rename("size").reset_index()
    merged = stats.merge(sizes, on=cluster_col)

    # purity
    top = (
        merged.sort_values("count", ascending=False)
        .groupby(cluster_col)
        .first()
        .reset_index()
    )
    top["purity"] = top["count"] / top["size"]
    top["impurity"] = 1 - top["purity"]

    # entropy
    entropy = (
        merged.assign(p=lambda x: x["count"] / x["size"])
        .groupby(cluster_col)
        .apply(lambda g: -np.sum(g["p"] * np.log(g["p"])))
        .reset_index(name="entropy")
    )

    return top.merge(entropy, on=cluster_col).sort_values("impurity", ascending=False)

In [22]:
quality_df = cluster_quality(sample_df, "C_id_agg", LABEL_COL)

# Worst clusters by impurity
quality_df.head(1000)

/var/folders/b_/cv34fjz13m34nzs9_x_gpp600000gn/T/ipykernel_63772/315832772.py:26: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: -np.sum(g["p"] * np.log(g["p"])))

,C_id_agg,Level3,count,size,purity,impurity,entropy
157,157,Server Barebones,499,3783,0.131906,0.868094,2.215587
362,362,Audio Cables,2,12,0.166667,0.833333,2.253858
57,57,Audio Cables,29,143,0.202797,0.797203,2.214439
36,36,HDMI Cables,413,1861,0.221924,0.778076,2.133319
83,83,Signage Displays,499,2220,0.224775,0.775225,1.655181
132,132,Battery Chargers,2,8,0.250000,0.750000,1.386294
296,296,Flat Panel Mount Accessories,13,49,0.265306,0.734694,1.727283
7,7,Flat Panel Desk Mounts,454,1703,0.266588,0.733412,1.695108
370,370,USB Cables,24,86,0.279070,0.720930,2.229531
34,34,Portable Speakers,404,1438,0.280946,0.719054,1.803134
311,311,USB Cables,4,14,0.285714,0.714286,1.809514
53,53,Mobile Device Keyboards,3,10,0.300000,0.700000,1.504788
151,151,Video Converters,3,10,0.300000,0.700000,1.695743
137,137,DisplayPort Cables,4,13,0.307692,0.692308,1.631345
52,52,Mobile Device Chargers,23,73,0.315068,0.684932,1.796281
110,110,Mobile Device Dock Stations,9,28,0.321429,0.678571,1.495840
139,139,Mobile Device Dock Stations,10,31,0.322581,0.677419,1.524476
318,318,Serial Cables,1,3,0.333333,0.666667,1.098612
127,127,Mobile Device Chargers,1,3,0.333333,0.666667,1.098612
191,191,Flat Panel Mount Accessories,2,6,0.333333,0.666667,1.560710
2,2,Flat Panel Accessories,11,33,0.333333,0.666667,1.659923
170,170,Serial Attached SCSI (SAS) Cables,201,602,0.333887,0.666113,2.027050
183,183,Radios,63,183,0.344262,0.655738,1.764578
330,330,Portable Speakers,26,75,0.346667,0.653333,1.546855
352,352,Power Adapters & Inverters,6,17,0.352941,0.647059,1.452044
189,189,Mobile Phone Cases,22,61,0.360656,0.639344,1.600292
37,37,Audio Cables,423,1137,0.372032,0.627968,1.949151
143,143,TVs,6,16,0.375000,0.625000,1.461472
98,98,Loudspeakers,12,32,0.375000,0.625000,1.536333
44,44,Smartphones,495,1308,0.378440,0.621560,1.144329
338,338,Tablet Spare Parts,23,59,0.389831,0.610169,1.509789
23,23,Wireless Routers,499,1271,0.392604,0.607396,1.525344
356,356,Installation Services,2,5,0.400000,0.600000,1.332179
262,262,Tablet Cases,2,5,0.400000,0.600000,1.332179
353,353,Digital Media Players,2,5,0.400000,0.600000,1.054920
43,43,MP3/MP4 Players,489,1191,0.410579,0.589421,1.718105
126,126,Mobile Phone Cases,7,17,0.411765,0.588235,1.149152
100,100,IT Support Services,285,685,0.416058,0.583942,1.208773
165,165,Fibre Optic Cables,484,1163,0.416165,0.583835,1.240680
45,45,Notebooks,24,57,0.421053,0.578947,1.448463
90,90,Serial Attached SCSI (SAS) Cables,51,120,0.425000,0.575000,1.928380
350,350,Power Cables,3,7,0.428571,0.571429,1.475076
68,68,Network Switch Components,3,7,0.428571,0.571429,1.277034
286,286,Video Cable Adapters,3,7,0.428571,0.571429,1.277034
328,328,Cable Interface/Gender Adapters,3,7,0.428571,0.571429,1.277034
173,173,Mobile Phone Cases,16,36,0.444444,0.555556,1.294771
131,131,Mobile Device Dock Stations,12,27,0.444444,0.555556,1.482636
42,42,Keyboards,259,578,0.448097,0.551903,1.136820
67,67,Handheld Device Accessories,20,44,0.454545,0.545455,1.438537
210,210,Stylus Pens,6,13,0.461538,0.538462,1.204793
69,69,Flat Panel Accessories,7,15,0.466667,0.533333,1.171060
66,66,DVD/Blu-Ray Players,451,966,0.466874,0.533126,1.065324
61,61,Tablet Cases,10,21,0.476190,0.523810,1.006386
219,219,Power Distribution Units (PDUs),493,1024,0.481445,0.518555,0.874242
73,73,Mobile Device Keyboards,236,488,0.483607,0.516393,0.992908
86,86,Projector Lamps,500,1031,0.484966,0.515034,0.846905
162,162,Power Banks,387,780,0.496154,0.503846,1.050056
321,321,MP3/MP4 Player Cases,1,2,0.500000,0.500000,0.693147
278,278,Digital Media Players,4,8,0.500000,0.500000,1.213008
284,284,Cable Interface/Gender Adapters,1,2,0.500000,0.500000,0.693147
280,280,Power Supply Units,3,6,0.500000,0.500000,1.011404
292,292,Mobile Device Dock Stations,1,2,0.500000,0.500000,0.693147
104,104,Handheld Device Accessories,2,4,0.500000,0.500000,1.039721
122,122,Flat Panel Desk Mounts,1,2,0.500000,0.500000,0.693147
121,121,Warranty & Support Extensions,1,2,0.500000,0.500000,0.693147
118,118,Coaxial Cables,2,4,0.500000,0.500000,1.039721
141,141,Battery Chargers,1,2,0.500000,0.500000,0.693147
105,105,Loudspeakers,8,16,0.500000,0.500000,0.974315
399,399,Software Licenses/Upgrades,2,4,0.500000,0.500000,0.693147
111,111,Handheld Device Accessories,1,2,0.500000,0.500000,0.693147
115,115,Component (YPbPr) Video Cables,3,6,0.500000,0.500000,1.011404
359,359,Handheld Device Accessories,1,2,0.500000,0.500000,0.693147
144,144,Servers,1,2,0.500000,0.500000,0.693147
159,159,Input Device Accessories,3,6,0.500000,0.500000,1.242453
221,221,Wire Connectors,1,2,0.500000,0.500000,0.693147
218,218,Flat Panel Floor Stands,1,2,0.500000,0.500000,0.693147
234,234,Mobile Phone Spare Parts,1,2,0.500000,0.500000,0.693147
371,371,Flat Panel Desk Mounts,1,2,0.500000,0.500000,0.693147
207,207,Office Suites,1,2,0.500000,0.500000,0.693147
195,195,InfiniBand Cables,5,10,0.500000,0.500000,1.029653
193,193,Cable Interface/Gender Adapters,1,2,0.500000,0.500000,0.693147
186,186,AV Extenders,3,6,0.500000,0.500000,1.242453
380,380,Digital Media Players,5,10,0.500000,0.500000,1.359237
341,341,Stylus Pens,2,4,0.500000,0.500000,1.039721
181,181,Input Device Accessories,1,2,0.500000,0.500000,0.693147
178,178,Handheld Device Accessories,2,4,0.500000,0.500000,0.693147
340,340,Remote Controls,2,4,0.500000,0.500000,1.039721
175,175,Cable Interface/Gender Adapters,7,14,0.500000,0.500000,0.992282
256,256,Holders,1,2,0.500000,0.500000,0.693147
167,167,Mobile Headsets,1,2,0.500000,0.500000,0.693147
225,225,Battery Chargers,1,2,0.500000,0.500000,0.693147
385,385,Flat Panel Spare Parts,1,2,0.500000,0.500000,0.693147
305,305,Projector Accessories,1,2,0.500000,0.500000,0.693147
50,50,Wire Connectors,6,12,0.500000,0.500000,1.314374
5,5,Maintenance & Support Fees,121,242,0.500000,0.500000,0.807577
413,413,Power Supply Units,3,6,0.500000,0.500000,0.693147
412,412,Computer Monitors,1,2,0.500000,0.500000,0.693147
40,40,Handheld Device Accessories,2,4,0.500000,0.500000,1.039721
8,8,Tablet Cases,6,12,0.500000,0.500000,1.473502
25,25,Handheld Device Accessories,6,12,0.500000,0.500000,1.314374
72,72,PC/Workstation Barebones,1,2,0.500000,0.500000,0.693147
60,60,Flat Panel Mount Accessories,1,2,0.500000,0.500000,0.693147
84,84,Flat Panel Accessories,1,2,0.500000,0.500000,0.693147
102,102,AV Extenders,34,66,0.515152,0.484848,1.350566
113,113,Radios,48,93,0.516129,0.483871,1.390321
32,32,AV Extenders,316,595,0.531092,0.468908,1.245505
172,172,Projector Accessories,16,30,0.533333,0.466667,1.333082
349,349,Mobile Phone Spare Parts,47,87,0.540230,0.459770,1.270200
41,41,Serial Cables,83,153,0.542484,0.457516,1.226121
38,38,USB Cables,368,678,0.542773,0.457227,1.209524
106,106,Patch Panels,6,11,0.545455,0.454545,0.689009
332,332,Flat Panel Floor Stands,11,20,0.550000,0.450000,1.373469
3,3,Mobile Device Dock Stations,10,18,0.555556,0.444444,1.457125
184,184,AV Extenders,5,9,0.555556,0.444444,0.936888
18,18,Remote Controls,4,7,0.571429,0.428571,0.682908
99,99,Antivirus Security Software,483,842,0.573634,0.426366,0.793137
59,59,Projector Mounts,465,808,0.575495,0.424505,1.201304
95,95,Network Switch Components,15,26,0.576923,0.423077,0.681266
79,79,KVM Switches,452,760,0.594737,0.405263,0.767584
182,182,Battery Chargers,49,82,0.597561,0.402439,1.134818
309,309,Network Transceiver Modules,477,798,0.597744,0.402256,0.818031
16,16,Smartwatches,183,306,0.598039,0.401961,0.673799
54,54,InfiniBand Cables,3,5,0.600000,0.400000,0.673012
150,150,Power Banks,72,120,0.600000,0.400000,1.307209
294,294,Battery Chargers,3,5,0.600000,0.400000,0.950271
310,310,Handheld Device Accessories,6,10,0.600000,0.400000,1.088900
351,351,Power Supply Units,3,5,0.600000,0.400000,0.673012
242,242,Flat Panel Accessories,3,5,0.600000,0.400000,0.673012
94,94,Print Servers,3,5,0.600000,0.400000,0.673012
47,47,Office Suites,85,139,0.611511,0.388489,0.668067
308,308,Tablet Cases,13,21,0.619048,0.380952,0.928585
264,264,Projector Accessories,53,85,0.623529,0.376471,1.142307
0,0,Household Batteries,173,277,0.624549,0.375451,1.056924
360,360,Installation Services,5,8,0.625000,0.375000,0.661563
149,149,Wire Connectors,5,8,0.625000,0.375000,1.073543
322,322,Serial Cables,10,16,0.625000,0.375000,0.830524
402,402,Remote Controls,7,11,0.636364,0.363636,0.859967
268,268,Input Device Accessories,7,11,0.636364,0.363636,1.033562
22,22,Operating Systems,7,11,0.636364,0.363636,0.655482
80,80,Cable Interface/Gender Adapters,7,11,0.636364,0.363636,1.033562
160,160,Handheld Device Accessories,11,17,0.647059,0.352941,0.955447
89,89,Flat Panel Accessories,23,35,0.657143,0.342857,0.741256
190,190,Flat Panel Wall Mounts,2,3,0.666667,0.333333,0.636514
238,238,Antivirus Security Software,14,21,0.666667,0.333333,0.636514
200,200,Warranty & Support Extensions,2,3,0.666667,0.333333,0.636514
199,199,Power Adapters & Inverters,2,3,0.666667,0.333333,0.636514
230,230,Docking Speakers,2,3,0.666667,0.333333,0.636514
153,153,Holders,2,3,0.666667,0.333333,0.636514
152,152,Projection Lenses,2,3,0.666667,0.333333,0.636514
411,411,Portable Speakers,2,3,0.666667,0.333333,0.636514
304,304,Flat Panel Desk Mounts,2,3,0.666667,0.333333,0.636514
361,361,MP3/MP4 Players,2,3,0.666667,0.333333,0.636514
140,140,Power Supply Units,4,6,0.666667,0.333333,0.867563
112,112,Cable Interface/Gender Adapters,2,3,0.666667,0.333333,0.636514
133,133,Flat Panel Mount Accessories,2,3,0.666667,0.333333,0.636514
81,81,Projector Accessories,2,3,0.666667,0.333333,0.636514
396,396,Video Splitters,2,3,0.666667,0.333333,0.636514
74,74,USB Cables,2,3,0.666667,0.333333,0.636514
289,289,WLAN Access Points,2,3,0.666667,0.333333,0.636514
180,180,Household Batteries,140,208,0.673077,0.326923,0.631978
397,397,Warranty & Support Extensions,27,40,0.675000,0.325000,0.630581
17,17,Flat Panel Wall Mounts,29,42,0.690476,0.309524,0.956286
46,46,Installation Services,41,59,0.694915,0.305085,0.979537
171,171,Mobile Device Chargers,7,10,0.700000,0.300000,0.801819
188,188,Power Supply Units,12,17,0.705882,0.294118,0.605797
136,136,Flat Panel Spare Parts,488,688,0.709302,0.290698,0.901158
14,14,Power Cables,438,607,0.721582,0.278418,0.946089
31,31,Operating Systems,32,44,0.727273,0.272727,0.922571
77,77,Tablet Spare Parts,18,24,0.750000,0.250000,0.894750
192,192,Wire Connectors,3,4,0.750000,0.250000,0.562335
10,10,Power Distribution Units (PDUs),3,4,0.750000,0.250000,0.562335
114,114,Remote Controls,3,4,0.750000,0.250000,0.562335
320,320,WLAN Access Points,3,4,0.750000,0.250000,0.562335
135,135,Mobile Phone Cables,3,4,0.750000,0.250000,0.562335
28,28,Battery Chargers,6,8,0.750000,0.250000,0.562335
129,129,Household Batteries,177,230,0.769565,0.230435,0.762661
21,21,SATA Cables,157,202,0.777228,0.222772,0.851547
56,56,Mice,21,27,0.777778,0.222222,0.671154
176,176,Handheld Device Accessories,7,9,0.777778,0.222222,0.529706
24,24,Battery Chargers,170,218,0.779817,0.220183,0.820032
168,168,Handheld Device Accessories,11,14,0.785714,0.214286,0.754997
227,227,Software Licenses/Upgrades,11,14,0.785714,0.214286,0.519580
269,269,Audio Cables,4,5,0.800000,0.200000,0.500402
376,376,Projector Accessories,4,5,0.800000,0.200000,0.500402
4,4,KVM Switches,4,5,0.800000,0.200000,0.500402
163,163,Battery Chargers,4,5,0.800000,0.200000,0.500402
20,20,Network Switches,428,525,0.815238,0.184762,0.645091
88,88,IT Support Services,148,178,0.831461,0.168539,0.478194
201,201,Flat Panel Desk Mounts,25,30,0.833333,0.166667,0.672591
272,272,Handheld Device Accessories,5,6,0.833333,0.166667,0.450561
55,55,Holders,58,69,0.840580,0.159420,0.597318
65,65,Tablet Cases,377,446,0.845291,0.154709,0.640986
109,109,Handheld Device Accessories,17,20,0.850000,0.150000,0.518186
295,295,Mobile Phone Cables,6,7,0.857143,0.142857,0.410116
82,82,Radios,258,301,0.857143,0.142857,0.574247
19,19,Flat Panel Accessories,13,15,0.866667,0.133333,0.485094
26,26,Operating Systems,46,53,0.867925,0.132075,0.480509
161,161,MP3/MP4 Player Cases,208,239,0.870293,0.129707,0.492508
39,39,Flat Panel Accessories,47,54,0.870370,0.129630,0.438845
33,33,Projection Screens,492,563,0.873890,0.126110,0.503864
101,101,IT Support Services,7,8,0.875000,0.125000,0.376770
51,51,Mobile Phones,7,8,0.875000,0.125000,0.376770
35,35,Coaxial Cables,7,8,0.875000,0.125000,0.376770
241,241,Input Device Accessories,7,8,0.875000,0.125000,0.376770
12,12,Mobile Phone Cases,377,427,0.882904,0.117096,0.543765
346,346,Wire Connectors,8,9,0.888889,0.111111,0.348832
154,154,AV Extenders,8,9,0.888889,0.111111,0.348832
377,377,Installation Services,9,10,0.900000,0.100000,0.325083
63,63,KVM Switches,27,30,0.900000,0.100000,0.388734
30,30,Warranty & Support Extensions,28,31,0.903226,0.096774,0.317937
204,204,Digital Photo Frames,117,129,0.906977,0.093023,0.351390
1,1,Projection Lenses,130,142,0.915493,0.084507,0.289641
49,49,Network Antennas,115,124,0.927419,0.072581,0.309890
158,158,Input Device Accessories,45,48,0.937500,0.062500,0.273574
76,76,Stylus Pens,285,304,0.937500,0.062500,0.323173
64,64,Battery Chargers,15,16,0.937500,0.062500,0.233792
96,96,E-Book Reader Cases,121,128,0.945312,0.054688,0.244810
329,329,Display Privacy Filters,494,520,0.950000,0.050000,0.206666
120,120,Mobile Phone Spare Parts,400,421,0.950119,0.049881,0.239687
58,58,Power Adapters & Inverters,458,482,0.950207,0.049793,0.233917
142,142,Thin Clients,43,45,0.955556,0.044444,0.212627
147,147,POS Systems,22,23,0.956522,0.043478,0.178845
75,75,Mobile Headsets,484,506,0.956522,0.043478,0.229868
290,290,Projector Accessories,25,26,0.961538,0.038462,0.163024
198,198,Remote Controls,25,26,0.961538,0.038462,0.163024
29,29,Mouse Pads,161,167,0.964072,0.035928,0.170968
164,164,Screen Protectors,444,460,0.965217,0.034783,0.172596
27,27,Power Supply Units,392,405,0.967901,0.032099,0.175082
317,317,UPS Batteries,386,398,0.969849,0.030151,0.179519
148,148,Holders,108,111,0.972973,0.027027,0.124251
373,373,Software Licenses/Upgrades,105,107,0.981308,0.018692,0.092902
93,93,Mice,459,467,0.982869,0.017131,0.102073
138,138,Projector Accessories,79,80,0.987500,0.012500,0.067197
398,398,Remote Controls,251,253,0.992095,0.007905,0.046137
355,355,Wire Connectors,1,1,1.000000,0.000000,-0.000000
316,316,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
363,363,Flat Panel Accessories,1,1,1.000000,0.000000,-0.000000
415,415,Holders,1,1,1.000000,0.000000,-0.000000
392,392,Internal Power Cables,1,1,1.000000,0.000000,-0.000000
319,319,Notebooks,1,1,1.000000,0.000000,-0.000000
414,414,Projector Accessories,2,2,1.000000,0.000000,-0.000000
391,391,Installation Services,1,1,1.000000,0.000000,-0.000000
315,315,Wired Routers,3,3,1.000000,0.000000,-0.000000
390,390,Mobile Device Chargers,1,1,1.000000,0.000000,-0.000000
323,323,Calculators,1,1,1.000000,0.000000,-0.000000
324,324,Cable Interface/Gender Adapters,3,3,1.000000,0.000000,-0.000000
408,408,Operating Systems,1,1,1.000000,0.000000,-0.000000
325,325,Servers,1,1,1.000000,0.000000,-0.000000
326,326,Mice,3,3,1.000000,0.000000,-0.000000
407,407,Flat Panel Floor Stands,1,1,1.000000,0.000000,-0.000000
416,416,Installation Services,2,2,1.000000,0.000000,-0.000000
389,389,Flat Panel Accessories,1,1,1.000000,0.000000,-0.000000
314,314,Tablet Cases,1,1,1.000000,0.000000,-0.000000
313,313,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
393,393,Flat Panel Accessories,1,1,1.000000,0.000000,-0.000000
394,394,Mobile Phone Cables,1,1,1.000000,0.000000,-0.000000
312,312,Internal Power Cables,2,2,1.000000,0.000000,-0.000000
395,395,AV Extenders,1,1,1.000000,0.000000,-0.000000
406,406,KVM Switches,1,1,1.000000,0.000000,-0.000000
405,405,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
400,400,Remote Controls,15,15,1.000000,0.000000,-0.000000
401,401,Flat Panel Mount Accessories,3,3,1.000000,0.000000,-0.000000
404,404,Mobile Device Chargers,1,1,1.000000,0.000000,-0.000000
403,403,Projector Accessories,3,3,1.000000,0.000000,-0.000000
307,307,Cable Interface/Gender Adapters,3,3,1.000000,0.000000,-0.000000
306,306,Projector Mounts,2,2,1.000000,0.000000,-0.000000
409,409,Loudspeakers,4,4,1.000000,0.000000,-0.000000
327,327,Input Device Accessories,1,1,1.000000,0.000000,-0.000000
354,354,Mouse Pads,3,3,1.000000,0.000000,-0.000000
375,375,Software Licenses/Upgrades,1,1,1.000000,0.000000,-0.000000
344,344,Power Supply Units,1,1,1.000000,0.000000,-0.000000
345,345,Calculators,1,1,1.000000,0.000000,-0.000000
379,379,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
347,347,Holders,1,1,1.000000,0.000000,-0.000000
348,348,Projector Accessories,3,3,1.000000,0.000000,-0.000000
378,378,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
374,374,Remote Controls,1,1,1.000000,0.000000,-0.000000
342,342,Maintenance & Support Fees,2,2,1.000000,0.000000,-0.000000
365,365,KVM Cables,3,3,1.000000,0.000000,-0.000000
372,372,Calculators,1,1,1.000000,0.000000,-0.000000
369,369,Software Licenses/Upgrades,1,1,1.000000,0.000000,-0.000000
368,368,Network Antennas,2,2,1.000000,0.000000,-0.000000
367,367,Network Antennas,1,1,1.000000,0.000000,-0.000000
366,366,Operating Systems,3,3,1.000000,0.000000,-0.000000
343,343,All-in-One PCs/Workstations,1,1,1.000000,0.000000,-0.000000
381,381,Remote Controls,1,1,1.000000,0.000000,-0.000000
388,388,PCs/Workstations,1,1,1.000000,0.000000,-0.000000
333,333,Flat Panel Spare Parts,1,1,1.000000,0.000000,-0.000000
358,358,Software Licenses/Upgrades,2,2,1.000000,0.000000,-0.000000
357,357,SCSI Cables,1,1,1.000000,0.000000,-0.000000
386,386,Projector Accessories,1,1,1.000000,0.000000,-0.000000
410,410,Display Privacy Filters,1,1,1.000000,0.000000,-0.000000
331,331,Handheld Device Accessories,3,3,1.000000,0.000000,-0.000000
364,364,Input Device Accessories,2,2,1.000000,0.000000,-0.000000
334,334,Handheld Device Accessories,1,1,1.000000,0.000000,-0.000000
382,382,Holders,2,2,1.000000,0.000000,-0.000000
335,335,E-Book Reader Cases,1,1,1.000000,0.000000,-0.000000
384,384,Coaxial Cables,1,1,1.000000,0.000000,-0.000000
336,336,Flat Panel Mount Accessories,1,1,1.000000,0.000000,-0.000000
337,337,Handheld Device Accessories,3,3,1.000000,0.000000,-0.000000
383,383,Cable Interface/Gender Adapters,1,1,1.000000,0.000000,-0.000000
339,339,Power Adapters & Inverters,1,1,1.000000,0.000000,-0.000000
387,387,Data Projectors,1,1,1.000000,0.000000,-0.000000
209,209,Embedded Computers,1,1,1.000000,0.000000,-0.000000
303,303,Input Device Accessories,1,1,1.000000,0.000000,-0.000000
145,145,Keyboards,2,2,1.000000,0.000000,-0.000000
155,155,Operating Systems,139,139,1.000000,0.000000,-0.000000
156,156,Holders,51,51,1.000000,0.000000,-0.000000
166,166,Installation Services,1,1,1.000000,0.000000,-0.000000
169,169,Power Supply Units,41,41,1.000000,0.000000,-0.000000
174,174,Holders,2,2,1.000000,0.000000,-0.000000
177,177,Keyboards,4,4,1.000000,0.000000,-0.000000
179,179,Handheld Device Accessories,2,2,1.000000,0.000000,-0.000000
185,185,Handheld Device Accessories,2,2,1.000000,0.000000,-0.000000
187,187,Remote Controls,6,6,1.000000,0.000000,-0.000000
194,194,Flat Panel Accessories,3,3,1.000000,0.000000,-0.000000
196,196,Mobile Device Dock Stations,4,4,1.000000,0.000000,-0.000000
197,197,Software Licenses/Upgrades,5,5,1.000000,0.000000,-0.000000
202,202,Patch Panels,24,24,1.000000,0.000000,-0.000000
203,203,InfiniBand Cables,5,5,1.000000,0.000000,-0.000000
205,205,PC/Workstation Barebones,2,2,1.000000,0.000000,-0.000000
206,206,Wired Routers,3,3,1.000000,0.000000,-0.000000
208,208,Network Switch Components,1,1,1.000000,0.000000,-0.000000
211,211,Software Licenses/Upgrades,1,1,1.000000,0.000000,-0.000000
212,212,Projector Accessories,1,1,1.000000,0.000000,-0.000000
213,213,Mobile Phone Cases,1,1,1.000000,0.000000,-0.000000
214,214,Wired Routers,1,1,1.000000,0.000000,-0.000000
215,215,Battery Chargers,1,1,1.000000,0.000000,-0.000000
216,216,Flat Panel Accessories,2,2,1.000000,0.000000,-0.000000
217,217,Patch Panels,1,1,1.000000,0.000000,-0.000000
220,220,IT Support Services,50,50,1.000000,0.000000,-0.000000
146,146,Mobile Phone Spare Parts,2,2,1.000000,0.000000,-0.000000
134,134,Remote Controls,6,6,1.000000,0.000000,-0.000000
302,302,Mobile Headsets,1,1,1.000000,0.000000,-0.000000

In [23]:
example_cluster = sample_df["C_id_agg"].value_counts().index[49]

sample_df[sample_df["C_id_agg"] == example_cluster][["Brand", "ProductName", LABEL_COL]].head(1000)

,Brand,ProductName,Level3
2495,StarTech.com,Micro SATA to SATA Adapter Cable with Power,Cable Interface/Gender Adapters
2534,Techly,USB3.0 to IDE + SATA II Converter,Cable Interface/Gender Adapters
2555,ACT,"Micro SATA(6+7) male - SATA(7) + 5,25"" male (4 pins)Micro SATA(6+7) male - SATA(7) + 5,25"" male (4 pins)",Cable Interface/Gender Adapters
2573,Equip,USB 2.0 SATA/IDE,Cable Interface/Gender Adapters
2578,Techly,USB 3.0 Adapter to Serial ATA IUSB3-SATA2,Cable Interface/Gender Adapters
2580,Conceptronic,SATA to USB 3.0 Adapter,Cable Interface/Gender Adapters
2665,Sandberg,"Adapter kit 2.5"" HDD to 3.5""",Cable Interface/Gender Adapters
2757,j5 create,JEE254,Cable Interface/Gender Adapters
2759,StarTech.com,USB 3.1 (10Gbps) Adapter Cable for 2.5”/3.5” SATA Drives - USB-C,Cable Interface/Gender Adapters
2822,StarTech.com,3 ft SuperSpeed USB 3.0 to eSATA Cable Adapter,Cable Interface/Gender Adapters
2896,StarTech.com,"USB 3.1 (10Gbps) Adapter Cable for 2.5"" SATA Drives",Cable Interface/Gender Adapters
2913,iggual,IGG312919,Cable Interface/Gender Adapters
2937,StarTech.com,Bi-Directional SATA IDE Adapter Converter,Cable Interface/Gender Adapters
2946,j5 create,JEE252,Cable Interface/Gender Adapters
14268,Ewent,EW9170,Internal Power Cables
14271,StarTech.com,12in LP4 to 2x Right Angle Latching SATA Power Y Cable Splitter - 4 Pin LP4 to Dual SATA,Internal Power Cables
14272,StarTech.com,SATA to LP4 Power Cable Adapter with 2 Additional LP4,Internal Power Cables
14283,StarTech.com,LP4 to SATA Power Cable Adapter with Floppy Power,Internal Power Cables
14285,StarTech.com,SATA to LP4 with 2x SATA Power Splitter Cable,Internal Power Cables
14295,Tripp Lite,"Serial ATA (SATA) Power Cable (4Pin Molex to 15pin), 15.24 cm",Internal Power Cables
14304,StarTech.com,8in 15 pin SATA Power Extension Cable,Internal Power Cables
14313,ACT,SATA bracketSATA bracket,Internal Power Cables
14358,ACT,Serial ATA II Power Adapter,Internal Power Cables
14362,StarTech.com,6in 4 Pin LP4 to SATA Power Cable Adapter,Internal Power Cables
14380,Equip,"SATA power supply cable, 1.0m",Internal Power Cables
14387,StarTech.com,18in SAS 29 Pin to SATA Cable with LP4 Power,Internal Power Cables
14390,ACT,Serial ATA powersplitter,Internal Power Cables
14394,Ewent,EW9170,Internal Power Cables
14404,StarTech.com,2.5in IDE Hard Drive to 3.5in Drive Bay Mounting Kit,Internal Power Cables
14405,ACT,Serial ATA power splitter cable,Internal Power Cables
14412,StarTech.com,6in SATA Power Y Splitter Cable Adapter - M/F,Internal Power Cables
14416,StarTech.com,4x SATA Power Splitter Adapter Cable,Internal Power Cables
14441,StarTech.com,6in Latching SATA Power Y Splitter Cable Adapter - M/F,Internal Power Cables
14442,Equip,SATA Internal Power Cable,Internal Power Cables
14453,ACT,Serial ATA Power Adapter cable,Internal Power Cables
27583,Intel,ATA Flash Drive Power Cable,Power Cables
27604,ACT,Serial ATA power splitter cable,Power Cables
28303,StarTech.com,18in Single Drive Round Floppy Cable - Grey,Power Supply Units
32078,Tripp Lite,"Serial atA (SatA) Latching Signal Cable (7Pin/7Pin), 19-in.",SATA Cables
32079,C2G,2m External Serial ATA Cable,SATA Cables
32080,Equip,"SATA III Cable, 0.5m",SATA Cables
32085,StarTech.com,18in Latching SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32087,C2G,Serial ATA to External Serial ATA Dual Port Adapter,SATA Cables
32088,StarTech.com,Retail 18 Inch Serial ATA Data Cable in blister package,SATA Cables
32089,Fujitsu,S26361-F2581-L36,SATA Cables
32090,C2G,Serial ATA Converter Board,SATA Cables
32091,C2G,"Go!Mod Molded Round 2-Device Ultra ATA133 EIDE Cable, UV Blue 36""",SATA Cables
32092,C2G,2m Serial ATA to External Serial ATA Cable,SATA Cables
32093,Techly,SATA 50 cm,SATA Cables
32094,Sandberg,eSATA-SATA Adapter,SATA Cables
32095,ACT,Conversion cable eSata - SATAConversion cable eSata - SATA,SATA Cables
32096,C2G,36in 7-pin Serial ATA Device Cable,SATA Cables
32097,Conceptronic,SATA Data Cable,SATA Cables
32098,ACT,eSATA bracketeSATA bracket,SATA Cables
32099,StarTech.com,0.5m Slimline SATA Female to SATA with SATA Power Cable Adapter,SATA Cables
32100,Tripp Lite,"SATA to eSATA Transition Cable (7Pin/7Pin), 0.91 m (3-ft.)",SATA Cables
32102,iTek,3m SATAIII,SATA Cables
32105,Sandberg,"ATA133 cable, flat, 0.5 m",SATA Cables
32106,StarTech.com,18in SATA to Left Side Angle SATA Serial ATA Cable,SATA Cables
32107,iggual,IGG312582,SATA Cables
32109,Equip,"SATA II Cable, 0.5m",SATA Cables
32110,StarTech.com,2 Port SATA to eSATA Slot Plate Bracket,SATA Cables
32111,Sandberg,"ATA133 cable, flat, 1.5 m",SATA Cables
32113,Fujitsu,S26361-F5243-L1,SATA Cables
32114,StarTech.com,24in SATA to Left Angle SATA Serial ATA Cable,SATA Cables
32115,Tripp Lite,"eSATA, SATA-II External Signal Shielded Cable (7Pin/7Pin), 45.72 cm (18-in.)",SATA Cables
32116,iggual,IGG312544,SATA Cables
32117,HP,Cable-SATA,SATA Cables
32118,StarTech.com,12in Right Angle SATA Cable - Serial ATA F/F,SATA Cables
32119,C2G,24in Go!Mod Molded Round 1-Device Ultra ATA133 EIDE Cable - UV Reactive Blue,SATA Cables
32120,HP,709827-001,SATA Cables
32122,Equip,eSATA cable,SATA Cables
32124,StarTech.com,10in SATA Serial ATA Data and Power Combo Cable,SATA Cables
32125,StarTech.com,12in Latching SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32126,StarTech.com,12in Right Angle Latching Serial ATA SATA Cable,SATA Cables
32129,Conceptronic,CCSATA06,SATA Cables
32130,HP,656833-001,SATA Cables
32131,C2G,1m 7-pin 90° to 90° SATA Cable,SATA Cables
32132,StarTech.com,24in Latching SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32133,Sandberg,eSATA-SATA 7p-7p 2 m,SATA Cables
32135,ACT,Serial ATA combi cable,SATA Cables
32137,V7,SATA CABLE 7P-RA/7P,SATA Cables
32138,StarTech.com,24 inch Round ATA 100/133 IDE Cable,SATA Cables
32139,HP,638813-001,SATA Cables
32140,C2G,24in Go!Mod Molded Round 1-Device Ultra ATA133 EIDE Cable,SATA Cables
32141,Sandberg,"ATA133 cable, round, 0.8 m",SATA Cables
32142,V7,SATA-SATA 2m,SATA Cables
32144,Ewent,EW9172,SATA Cables
32146,Sandberg,SATA 3.0 cable 0.8m angled,SATA Cables
32147,Sandberg,IDE drive to SATA power connector,SATA Cables
32149,StarTech.com,3 ft Power eSATA Male to eSATA Male and USB A Female Cable,SATA Cables
32150,ACT,SATA connection cable,SATA Cables
32152,C2G,1m UATA133 EIDE Cable,SATA Cables
32153,StarTech.com,18in SATA to Left Angle SATA Serial ATA Cable - F/F,SATA Cables
32154,StarTech.com,6in SATA Serial ATA Cable,SATA Cables
32155,StarTech.com,0.3m SATA Extension Cable,SATA Cables
32156,C2G,18in 7-pin 90°-side to 90°-side Serial ATA Device Cable,SATA Cables
32157,StarTech.com,6in SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32158,StarTech.com,36in Dual Drive Ultra ATA IDE Cable,SATA Cables
32159,iggual,IGG311790,SATA Cables
32160,StarTech.com,6in Latching SATA Cable,SATA Cables
32161,Equip,"eSATA ll Cable, 2.0m",SATA Cables
32162,HP,638814-001,SATA Cables
32163,StarTech.com,12in 22 Pin SATA Power and Data Extension Cable,SATA Cables
32164,StarTech.com,24in SATA Serial ATA Data and Power Combo Cable,SATA Cables
32165,C2G,2m 90° to 90° External Serial ATA Device Cable,SATA Cables
32168,C2G,"7-pin 180° to 90° Serial ATA Device Cable 36""",SATA Cables
32169,C2G,"Go!Mod Molded Round 2-Device Ultra ATA133 EIDE Cable, UV Reactive Blue 24""",SATA Cables
32170,StarTech.com,12in Slimline SATA to SATA with LP4 Power Cable Adapter,SATA Cables
32171,StarTech.com,8in SATA Serial ATA Cable,SATA Cables
32172,C2G,0.5m 7-pin SATA Cable,SATA Cables
32174,C2G,50020,SATA Cables
32176,iggual,PSICC-SATA,SATA Cables
32177,Ewent,EW-150102-003-Y-P,SATA Cables
32178,Intel,ASR2500SATA,SATA Cables
32179,Equip,"SATA II Cable, 1m",SATA Cables
32181,C2G,2m 180° to 90° External Serial ATA Device Cable,SATA Cables
32182,StarTech.com,24in SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32183,HP,667854-001,SATA Cables
32184,Philips,eSATA cable SWN2176/10,SATA Cables
32185,StarTech.com,18in Right Angle SATA Cable with LP4 Adapter,SATA Cables
32186,C2G,Economy Round Ultra ATA133 EIDE Cable 3ft,SATA Cables
32187,StarTech.com,18in Latching Round SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32188,StarTech.com,18in SATA Serial ATA Data and Power Combo Cable,SATA Cables
32189,StarTech.com,36 inch Round ATA 100/133 IDE Cable,SATA Cables
32193,C2G,1m 7-pin SATA Cable,SATA Cables
32196,StarTech.com,18in SATA Serial ATA Cable,SATA Cables
32198,Fujitsu,SNP:A3C40102755,SATA Cables
32200,StarTech.com,18in Latching SATA Cable,SATA Cables
32201,Tripp Lite,19-in. 7Pin/7Pin,SATA Cables
32203,StarTech.com,12in SATA to Right Side Angle SATA Serial ATA Cable,SATA Cables
32204,V7,Internal SATA Cable,SATA Cables
32205,StarTech.com,18in Right Angle SATA Cable - F/F,SATA Cables
32209,Tripp Lite,"Serial ATA (SATA) Latching Signal Cable (7Pin/7Pin), 20.32 cm (8-in.)",SATA Cables
32210,Tripp Lite,"Serial ATA (SATA) Right Angle Signal Cable (7Pin/7Pin-Up), 30.48 cm (12-in.)",SATA Cables
32211,Tripp Lite,"Serial ATA (SATA) Right Angle Signal Cable (7Pin/7Pin-Down), 60.96 cm (24-in.)",SATA Cables
32213,StarTech.com,8in SATA to Left Angle SATA Serial ATA Cable,SATA Cables
32215,C2G,36in Go!Mod Molded Round 1-Device Ultra ATA133 EIDE Cable - Black,SATA Cables
32216,StarTech.com,12in Micro SATA to SATA with LP4 Power Cable Adapter,SATA Cables
32217,StarTech.com,20in Slimline SATA to SATA with LP4 Power Cable Adapter,SATA Cables
32218,V7,8Q9075,SATA Cables
32219,StarTech.com,12in SATA to Left Side Angle SATA Serial ATA Cable,SATA Cables
32220,Tripp Lite,"Serial ATA (SATA) Right Angle Signal Cable (7Pin/7Pin-Up), 48.26 cm (19-in.)",SATA Cables
32221,StarTech.com,1 Port SATA to eSATA Slot Plate Bracket,SATA Cables
32222,C2G,36in Go!Mod Molded Round 2-Device Ultra ATA133 EIDE Cable,SATA Cables
32225,StarTech.com,24in SATA Serial ATA Cable,SATA Cables
32226,C2G,"7-pin Serial ATA Device Cable 18""",SATA Cables
32227,C2G,1m External Serial ATA Cable,SATA Cables
32229,Equip,"SATA III Cable, Angled, 0.5m",SATA Cables
32230,Nanocable,10.18.0401,SATA Cables
32232,HP,453317-001,SATA Cables
32233,ACT,Ultra ATA round cable,SATA Cables
32235,StarTech.com,12in Latching Round SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32236,StarTech.com,"36"" Shielded Serial ATA Cable",SATA Cables
32237,V7,SATA CABLE 7P-RA/7P,SATA Cables
32238,C2G,0.75m Ultra ATA133 EIDE Flat Ribbon Cable,SATA Cables
32240,StarTech.com,12in SATA to Left Angle SATA Serial ATA Cable,SATA Cables
32241,HP,Hard drive SATA cable,SATA Cables
32242,V7,USB 3.0 to SATA / IDE Adapter,SATA Cables
32243,C2G,Serial ATA to External Serial ATA Cable 1m,SATA Cables
32244,Equip,"SATA III Cable, 1m",SATA Cables
32245,Ewent,"0.5m, 6GBs, SATA 3",SATA Cables
32246,StarTech.com,18in SATA to Right Side Angle SATA Serial ATA Cable,SATA Cables
32247,StarTech.com,6in Latching Round SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32249,Sandberg,Serial ATA Cable 0.5 m,SATA Cables
32250,StarTech.com,1 Port SATA to SATA Slot Plate Bracket,SATA Cables
32251,Tripp Lite,"eSATA, SATA-II External Signal Shielded Cable (7Pin/7Pin), 91.44 cm (36-in.)",SATA Cables
32254,StarTech.com,6in SATA to Left Angle SATA Serial ATA Cable,SATA Cables
32255,C2G,"7-pin 90° to 90° Serial ATA Device Cable 18""",SATA Cables
32256,StarTech.com,12in Latching SATA Cable,SATA Cables
32257,StarTech.com,8in SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32258,Intel,ASR1550SATA,SATA Cables
32259,HP,639959-001,SATA Cables
32261,HP,646830-001,SATA Cables
32262,StarTech.com,24in Right Angle SATA Cable,SATA Cables
32263,C2G,10192,SATA Cables
32264,ACT,IDE HDD flatcableIDE HDD flatcable,SATA Cables
32265,HP,eSATA PCI Cable Kit,SATA Cables
32268,Sandberg,eSata 7p-7p 2 m,SATA Cables
32269,ACT,AK3415,SATA Cables
32270,Equip,"SATA II Cable, Angled, 1m",SATA Cables
32272,iggual,IGG311820,SATA Cables
32273,StarTech.com,36in SATA Power Cable Adapter,SATA Cables
32274,StarTech.com,6in Latching Round SATA Cable,SATA Cables
32276,Lenovo,4X90H04223,SATA Cables
32278,StarTech.com,2m Shielded External eSATA Cable M/M,SATA Cables
32279,iggual,IGG312575,SATA Cables
32280,StarTech.com,"24"" Latching SATA Cable M/M 2 Right Angle",SATA Cables
32281,StarTech.com,36in SATA to Right Angle SATA Serial ATA Cable,SATA Cables
32282,Sandberg,Serial ATA Power ada. 90 deg.,SATA Cables
32283,ACT,eSATA connection cableeSATA connection cable,SATA Cables
32285,HP,610958-001,SATA Cables
32286,Tripp Lite,"Serial ATA (SATA) Latching Signal Cable (7Pin/7Pin), 30.48 cm (12-in.)",SATA Cables
32287,iggual,IGG311837,SATA Cables
32288,StarTech.com,12in Micro SATA Extension Cable,SATA Cables
32312,StarTech.com,32-inch Universal Floppy Drive Cable,SCSI Cables
33049,Intel,6th SCSI Drive Kit - Storage Drive Kit,Serial Attached SCSI (SAS) Cables
33181,StarTech.com,20in Right Angle Slimline SATA to SATA w/ LP4 Power Cable,Serial Attached SCSI (SAS) Cables
33206,ACT,SATA II connection cableSATA II connection cable,Serial Cables
33283,ACT,SATA connection cable with hooked connectorSATA connection cable with hooked connector,Serial Cables
39864,Equip,133379,USB Cables
40297,j5 create,1.8m USB2.0 C - MiniUSB2.0 B,USB Cables

In [24]:
sample_df[sample_df["C_id_agg"] == 49][["Brand", "ProductName", LABEL_COL]].head(1000)

,Brand,ProductName,Level3
2861,Zyxel,Telco-50 to RJ-11 Cable,Cable Interface/Gender Adapters
3481,Zyxel,"Antenna cable, type N - type N, 12m",Coaxial Cables
3505,Zyxel,"Antenna cable, type N - SMA, 9m",Coaxial Cables
3545,Zyxel,"Antenna cable, type N - type N, 9m",Coaxial Cables
3577,Zyxel,"Antenna cable, type N - SMA, 3m",Coaxial Cables
3585,Zyxel,LMR-200 Antenna cable 9 m,Coaxial Cables
3587,Zyxel,"Antenna cable, type N - type N, 6m",Coaxial Cables
3613,Zyxel,LMR-400 Antenna cable 9 m,Coaxial Cables
21218,Zyxel,ANT1310,Network Antennas
21219,Zyxel,EXT 106,Network Antennas
21220,LevelOne,11a(5.500-5.825Ghz) 10dBi Omni-Direction Antenna Kit,Network Antennas
21221,LevelOne,9dBi 2.4GHz Omni-directional Outdoor Antenna,Network Antennas
21222,Allied Telesis,Omni Antenna,Network Antennas
21223,LevelOne,WAN-2121,Network Antennas
21224,D-Link,DWL-50AT,Network Antennas
21225,LevelOne,OAN-0501 2.4GHz Omni-Directional Antenna,Network Antennas
21227,Buffalo,14 dBi High Gain Outdoor Directional Antenna,Network Antennas
21228,Zyxel,ANT2105 Dual Pack,Network Antennas
21229,Zyxel,EXT-109 9 dBi Directional Patch Antenna,Network Antennas
21230,Zyxel,ANT1106 6dBi Omni-Directional Antenna,Network Antennas
21231,D-Link,ANT24-0502,Network Antennas
21232,LevelOne,10dBi 5GHz Omni-directional Antenna,Network Antennas
21235,LevelOne,WAN-2201,Network Antennas
21236,Allied Telesis,Sector Antenna,Network Antennas
21237,LevelOne,OAN-2121,Network Antennas
21238,LevelOne,18dBi 2.4GHz Directional Panel Antenna,Network Antennas
21239,LevelOne,WAN-1160,Network Antennas
21240,Zyxel,ANT-3108,Network Antennas
21241,Allied Telesis,Parabolic Antenna,Network Antennas
21242,D-Link,Ceiling-mounted Indoor Antenna,Network Antennas
21243,LevelOne,9 dBi Indoor/Outdoor Antenna Kit,Network Antennas
21244,Zyxel,ZyAIR EXT-105 - 5dBi Omnidirectional Desktop Antenna,Network Antennas
21245,LevelOne,18 dBi Outdoor Antenna,Network Antennas
21246,LevelOne,18dBi Directional Yagi Outdoor Antenna,Network Antennas
21247,Zyxel,ANT3108,Network Antennas
21248,LevelOne,11a 23dBi Directional Outdoor Panel Antenna,Network Antennas
21249,EnGenius,SA2216,Network Antennas
21250,D-Link,6dBi Indoor Directional Antenna,Network Antennas
21251,Zyxel,ZyAIR EXT-106 - Indoor 6dBi Directional Patch Antenna,Network Antennas
21252,Allied Telesis,Sector Antenna,Network Antennas
21253,Buffalo,WLE-AT-NDRHB,Network Antennas
21255,LevelOne,6 dBi Indoor Antenna,Network Antennas
21256,D-Link,ANT24-1202,Network Antennas
21257,Linksys,High Gain Antenna Kit for TNC Connectors,Network Antennas
21258,Zyxel,EXT-108 8dBi Omni Antenna - N-Type,Network Antennas
21259,Zyxel,EXT-118 Outdoor 18 dBi Directional Panel Antenna,Network Antennas
21260,Netgear,ProSafe 7 DBI Omni-Directional Antenna,Network Antennas
21262,ASUS,WL-ANT151,Network Antennas
21263,LevelOne,WAN-7151,Network Antennas
21264,EnGenius,ENH210EXT,Network Antennas
21265,LevelOne,18dBi Directional Panel Outdoor Antenna,Network Antennas
21266,LevelOne,15dBi 5GHz Directional Dual-Polarization Outdoor Panel Antenna,Network Antennas
21267,ASUS,WL-ANT157,Network Antennas
21268,Allied Telesis,Panel Antenna,Network Antennas
21269,Buffalo,WLE-2DA,Network Antennas
21270,Zyxel,ZyAIR EXT-118 - Outdoor 18 dBi Directional Panel Antenna,Network Antennas
21271,Eminent,nTENNA 10dBi Antenna Extension,Network Antennas
21272,LevelOne,WAN-4201,Network Antennas
21273,Zyxel,ANT3316,Network Antennas
21274,Zyxel,EXT-104 Indoor 4dBi Omnidirectional Ceiling Antenna,Network Antennas
21275,ASUS,WL-ANT168 high-gain antenna,Network Antennas
21276,Zyxel,ANT1313,Network Antennas
21278,D-Link,ANT24-1600N,Network Antennas
21279,Buffalo,High Gain Directional,Network Antennas
21280,D-Link,Directional panel high gain outdoor antenna,Network Antennas
21281,D-Link,ANT24-0230,Network Antennas
21282,EnGenius,ENSTATIONAC,Network Antennas
21284,LevelOne,OAN-0600,Network Antennas
21285,Netgear,ANT2511AC,Network Antennas
21286,Netgear,ProSafe Indoor/Outdoor 10dB 2x2 Directional Antenna,Network Antennas
21287,Netgear,ProSAFE,Network Antennas
21288,Allied Telesis,Parabolic Antenna,Network Antennas
21289,LevelOne,18dBi 2.4GHz Directional Yagi Antenna,Network Antennas
21290,D-Link,Directional 6dBi Indoor Desktop Antenna,Network Antennas
21291,LevelOne,3dBi Omni-Directional Ceiling Antenna Kit,Network Antennas
21294,EnGenius,SN-UL-AK20L,Network Antennas
21296,Linksys,WRT002ANT,Network Antennas
21297,ASUS,WL-ANT150 high-gain antenna,Network Antennas
21298,D-Link,ANT24-0700,Network Antennas
21299,LevelOne,14dBi 2.4GHz Directional Panel Antenna,Network Antennas
21300,Zyxel,ANT3315,Network Antennas
21301,Buffalo,6.5 dBi High Gain Omni Antenna,Network Antennas
21302,Buffalo,WLE-DA2,Network Antennas
21303,D-Link,ANT50-2000N,Network Antennas
21304,Buffalo,WLE-HG-NDC,Network Antennas
21306,Eminent,EM9001 nTENNA Antenna Extension,Network Antennas
21307,EnGenius,SN-UL-AK20L-IND,Network Antennas
21308,D-Link,Directional Yagi high gain antenna,Network Antennas
21309,D-Link,ANT24-0700,Network Antennas
21310,Gigabyte,GN-AT2030C,Network Antennas
21312,D-Link,ANTENNA,Network Antennas
21313,Zyxel,ANT2206,Network Antennas
21315,LevelOne,WAN-2182,Network Antennas
21316,D-Link,Directional 6dBi H70 V85 indoor patch antenna reverse SMA female conF,Network Antennas
21317,Zyxel,EXT-102,Network Antennas
21319,D-Link,Outdoor 15dBi High Gain Omni-Directional Antenna,Network Antennas
21320,EnGenius,ENH210,Network Antennas
21321,Zyxel,ZyAIR EXT-104 - 4dBi Omnidirectional Ceiling Antenna,Network Antennas
21322,D-Link,ANT70-1800,Network Antennas
21323,Zyxel,"EXT-105, 2,4 GHz Indoor 5dBi Omnidirectional Desktop Antenna",Network Antennas
21324,Zyxel,EXT-106 Indoor 6dBi Directional Patch Antenna,Network Antennas
21325,Netgear,ProSAFE,Network Antennas
21326,Allied Telesis,Panel Antenna,Network Antennas
21327,Zyxel,ANT2105,Network Antennas
21328,D-Link,5dBi High Gain Omni-Directional Antenna,Network Antennas
21329,D-Link,Omni-directional Outdoor Antenna,Network Antennas
21330,LevelOne,14dBi Directional Outdoor Panel Antenna,Network Antennas
21332,Netgear,ANT2405,Network Antennas
21333,Approx,APP10DB,Network Antennas
21334,LevelOne,14dBi Panel Directional Antenna,Network Antennas
21335,D-Link,ANT24-0600,Network Antennas
21336,D-Link,5dBi Omni-Directional Indoor Antenna,Network Antennas
21337,Conceptronic,5dBi High Omni Antenna,Network Antennas
21338,Vertiv,HGA51G-DIR30,Network Antennas
21339,EnGenius,SA5315,Network Antennas
21340,LevelOne,8.5 dBi In/Outdoor Antenna,Network Antennas
21341,Netgear,ANT24501B-10000S,Network Antennas
21342,Zyxel,ANT1314,Network Antennas
21344,Zyxel,ANT-3218,Network Antennas
21345,Allied Telesis,Omni Antenna,Network Antennas
21346,LevelOne,18dBi 5GHz Directional Dual-Polarization Outdoor Panel Antenna,Network Antennas
21348,Zyxel,ANT3218,Network Antennas
21349,Zyxel,ANT1310,Network Antennas
43123,Zyxel,EXT-300,Wire Connectors

In [25]:
sample_df[sample_df["C_id_agg"] == 49][["Brand", "ProductName", LABEL_COL]].nunique()

Brand           14
ProductName    117
Level3           4
dtype: int64

In [40]:
sample_df[sample_df["C_id_agg"] == 5][["Brand", "ProductName", LABEL_COL]].nunique()

Brand            7
ProductName    242
Level3           4
dtype: int64

In [51]:
sample_df[sample_df["C_id_agg"] == 200][["Brand", "ProductName", LABEL_COL]].head(100)

      Brand        ProductName       Level3
1921  Casio            MS-20NC  Calculators
1922  Sharp            EL-243S  Calculators
1923  Canon              F-604  Calculators
1924     HP                12c  Calculators
1925  Sharp           EL-339HB  Calculators
1926  Casio           SL-100NC  Calculators
1927  Casio        JW-200TV-RD  Calculators
1928  Sharp         EL-531XGVL  Calculators
1929  Sharp           EL-334FB  Calculators
1930     HP             10bII+  Calculators
1931     HP               40gs  Calculators
1932  Casio            SL-450L  Calculators
1933  Sharp          EL-2607PG  Calculators
1934  Casio            DR-T220  Calculators
1935  Sharp         EL-501XBWH  Calculators
1936  Sharp        EL-2630PIII  Calculators
1937  Casio          MS-8VERII  Calculators
1938  Canon         HS-1200TCG  Calculators
1939  Casio           SL-300NC  Calculators
1940  Casio            FX-82ES  Calculators
1941  Casio              HL-4A  Calculators
1942  Canon           MP120-MG  Calculators
1943  Canon           MP11DX-2  Calculators
1944  Sharp           EL-1750V  Calculators
1945  Sharp          EL-338GGY  Calculators
1946  Casio  Classwiz FX-350EX  Calculators
1947     HP     OfficeCalc 200  Calculators
1948  Sharp           EL-233SB  Calculators
1949  Canon     MP120-MG-es II  Calculators
1950  Casio      fx-991LA PLUS  Calculators
1951     HP              300s+  Calculators
1952  Canon            MP25-MG  Calculators
1953  Sharp        EL-W531XHGR  Calculators
1954  Casio      FX-115ES Plus  Calculators
1955  Casio       FX-85DE Plus  Calculators
1956  Casio           SL-300NC  Calculators
1957  Casio        SL-300NC-GN  Calculators
1958  Casio             MS-6NC  Calculators
1959  Casio           WD-320MT  Calculators
1960  Canon             F-720I  Calculators
1961  Casio            MS-300M  Calculators
1962  Canon           X MARK 1  Calculators
1963  Canon           LS-120PC  Calculators
1964  Sharp           EL-W211G  Calculators
1965  Sharp           EL-509XB  Calculators
1966  Casio            HR-8RCE  Calculators
1967  Canon             AS-120  Calculators
1968  Canon               F710  Calculators
1969  Sharp           EL-W200E  Calculators
1970  Casio           MS-88ECO  Calculators
1971  Canon        P1-DTSC HWB  Calculators
1972  Sharp           EL-243EB  Calculators
1973  Sharp           EL-1611P  Calculators
1974     HP         Quick Calc  Calculators
1975  Casio            HL-815L  Calculators
1976  Casio         SL-310TER+  Calculators
1977  Casio       SL-1000SC-BK  Calculators
1978  Canon            P170-DH  Calculators
1979     HP         Quick Calc  Calculators
1980  Canon           P23-DH V  Calculators
1981  Sharp       EL-W506XB-YL  Calculators
1982  Casio             MS-20S  Calculators
1983  Casio             MS-7UC  Calculators
1984  Casio       SL-1000SC-BU  Calculators
1985  Casio         MS-20UC-YG  Calculators
1986  Sharp         EL-R297BBK  Calculators
1987  Casio           DH-12TER  Calculators
1988  Casio            FX-82EX  Calculators
1989  Canon            LS-123k  Calculators
1990  Sharp           EL-1611V  Calculators
1991  Sharp           EL-520WB  Calculators
1992  Casio           MS-100MS  Calculators
1993  Canon           BP36-LTS  Calculators
1994     HP              Prime  Calculators
1995  Casio        JW-200SC-BK  Calculators
1996  Canon         TS-1200TCG  Calculators
1997  Sharp  EL M332 BBL - BLU  Calculators
1998  Canon          AS-2200RI  Calculators
1999  Sharp            EL-250S  Calculators
2000  Casio         FX-9860GII  Calculators
2001  Canon            LS-83TC  Calculators
2002  Casio        SL-310UC-GN  Calculators
2003     HP                12c  Calculators
2004  Canon           LS-103TC  Calculators
2005  Casio       ClassPad 330  Calculators
2006  Canon           BP-36LTS  Calculators
2007  Casio          SL-1100TV  Calculators
2008  Canon             F-502G  Calculators
2009  Canon             LS-82Z  Calculators
2010  Sharp           EL-501XB  Calculators
2011  Casio             KL-120  Calculators
2012  Casio              MS-8B  Calculators
2013  Sharp           EL-330ER  Calculators
2014  Sharp            EL-143S  Calculators
2015  Canon           MP120-MG  Calculators
2016  Casio          HR-150TEC  Calculators
2017     HP       EasyCalc 100  Calculators
2018  Sharp          EL-2901RH  Calculators
2019  Casio             HS8VER  Calculators
2020  Canon            F-715SG  Calculators

In [ ]:
sample_df["Level3"].head(2)